// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatSession = `-- name: CreateChatSession :exec
INSERT INTO chat_sessions (id, user_id, star_id, context_moment_ids, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateChatSessionParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	StarID           pgtype.UUID
	ContextMomentIds []pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) error {
	_, err := q.db.Exec(ctx, createChatSession,
		arg.ID,
		arg.UserID,
		arg.StarID,
		arg.ContextMomentIds,
		arg.CreatedAt,
	)
	return err
}

const getChatSessionByID = `-- name: GetChatSessionByID :one
SELECT id, user_id, star_id, context_moment_ids, created_at
FROM chat_sessions WHERE id = $1
`

func (q *Queries) GetChatSessionByID(ctx context.Context, id pgtype.UUID) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSessionByID, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StarID,
		&i.ContextMomentIds,
		&i.CreatedAt,
	)
	return i, err
}
