// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :exec
INSERT INTO chat_messages (id, user_id, session_id, role, content, referenced_moments, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateChatMessageParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	SessionID         pgtype.UUID
	Role              string
	Content           string
	ReferencedMoments []byte
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) error {
	_, err := q.db.Exec(ctx, createChatMessage,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ReferencedMoments,
		arg.CreatedAt,
	)
	return err
}

const listMessagesBySessionID = `-- name: ListMessagesBySessionID :many
SELECT id, user_id, session_id, role, content, referenced_moments, created_at
FROM chat_messages WHERE session_id = $1 ORDER BY created_at
`

func (q *Queries) ListMessagesBySessionID(ctx context.Context, sessionID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.ReferencedMoments,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
