// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: constellations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConstellation = `-- name: CreateConstellation :exec
INSERT INTO constellations (id, user_id, name, constellation_insight, star_ids, topic_prompts, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateConstellationParams struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Name                 string
	ConstellationInsight string
	StarIds              []pgtype.UUID
	TopicPrompts         []string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateConstellation(ctx context.Context, arg CreateConstellationParams) error {
	_, err := q.db.Exec(ctx, createConstellation,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ConstellationInsight,
		arg.StarIds,
		arg.TopicPrompts,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getConstellationByID = `-- name: GetConstellationByID :one
SELECT id, user_id, name, constellation_insight, star_ids, topic_prompts, created_at, updated_at
FROM constellations WHERE id = $1
`

func (q *Queries) GetConstellationByID(ctx context.Context, id pgtype.UUID) (Constellation, error) {
	row := q.db.QueryRow(ctx, getConstellationByID, id)
	var i Constellation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ConstellationInsight,
		&i.StarIds,
		&i.TopicPrompts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConstellationByStarID = `-- name: GetConstellationByStarID :one
SELECT id, user_id, name, constellation_insight, star_ids, topic_prompts, created_at, updated_at
FROM constellations WHERE star_ids @> ARRAY[$1]::UUID[]
`

func (q *Queries) GetConstellationByStarID(ctx context.Context, dollar_1 []pgtype.UUID) (Constellation, error) {
	row := q.db.QueryRow(ctx, getConstellationByStarID, dollar_1)
	var i Constellation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ConstellationInsight,
		&i.StarIds,
		&i.TopicPrompts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConstellationsByUserID = `-- name: ListConstellationsByUserID :many
SELECT id, user_id, name, constellation_insight, star_ids, topic_prompts, created_at, updated_at
FROM constellations WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListConstellationsByUserID(ctx context.Context, userID pgtype.UUID) ([]Constellation, error) {
	rows, err := q.db.Query(ctx, listConstellationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Constellation
	for rows.Next() {
		var i Constellation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ConstellationInsight,
			&i.StarIds,
			&i.TopicPrompts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConstellation = `-- name: UpdateConstellation :exec
UPDATE constellations SET name = $2, constellation_insight = $3, star_ids = $4, topic_prompts = $5, updated_at = $6
WHERE id = $1
`

type UpdateConstellationParams struct {
	ID                   pgtype.UUID
	Name                 string
	ConstellationInsight string
	StarIds              []pgtype.UUID
	TopicPrompts         []string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpdateConstellation(ctx context.Context, arg UpdateConstellationParams) error {
	_, err := q.db.Exec(ctx, updateConstellation,
		arg.ID,
		arg.Name,
		arg.ConstellationInsight,
		arg.StarIds,
		arg.TopicPrompts,
		arg.UpdatedAt,
	)
	return err
}
