// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: echos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEcho = `-- name: CreateEcho :exec
INSERT INTO echos (id, moment_id, user_id, matched_moment_ids, similarities, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEchoParams struct {
	ID               pgtype.UUID
	MomentID         pgtype.UUID
	UserID           pgtype.UUID
	MatchedMomentIds []pgtype.UUID
	Similarities     []float64
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateEcho(ctx context.Context, arg CreateEchoParams) error {
	_, err := q.db.Exec(ctx, createEcho,
		arg.ID,
		arg.MomentID,
		arg.UserID,
		arg.MatchedMomentIds,
		arg.Similarities,
		arg.CreatedAt,
	)
	return err
}

const getEchoByMomentID = `-- name: GetEchoByMomentID :one
SELECT id, moment_id, user_id, matched_moment_ids, similarities, created_at
FROM echos WHERE moment_id = $1
`

func (q *Queries) GetEchoByMomentID(ctx context.Context, momentID pgtype.UUID) (Echo, error) {
	row := q.db.QueryRow(ctx, getEchoByMomentID, momentID)
	var i Echo
	err := row.Scan(
		&i.ID,
		&i.MomentID,
		&i.UserID,
		&i.MatchedMomentIds,
		&i.Similarities,
		&i.CreatedAt,
	)
	return i, err
}

const listEchosByMomentIDs = `-- name: ListEchosByMomentIDs :many
SELECT id, moment_id, user_id, matched_moment_ids, similarities, created_at
FROM echos WHERE moment_id = ANY($1::uuid[])
`

func (q *Queries) ListEchosByMomentIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Echo, error) {
	rows, err := q.db.Query(ctx, listEchosByMomentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Echo
	for rows.Next() {
		var i Echo
		if err := rows.Scan(
			&i.ID,
			&i.MomentID,
			&i.UserID,
			&i.MatchedMomentIds,
			&i.Similarities,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
