// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedbacks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFeedback = `-- name: InsertFeedback :exec
INSERT INTO feedbacks (id, user_id, content, created_at) VALUES ($1, $2, $3, $4)
`

type InsertFeedbackParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertFeedback(ctx context.Context, arg InsertFeedbackParams) error {
	_, err := q.db.Exec(ctx, insertFeedback,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}
