// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInsight = `-- name: CreateInsight :exec
INSERT INTO insights (id, user_id, moment_id, echo_id, text, related_moment_ids, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateInsightParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	MomentID         pgtype.UUID
	EchoID           pgtype.UUID
	Text             string
	RelatedMomentIds []pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateInsight(ctx context.Context, arg CreateInsightParams) error {
	_, err := q.db.Exec(ctx, createInsight,
		arg.ID,
		arg.UserID,
		arg.MomentID,
		arg.EchoID,
		arg.Text,
		arg.RelatedMomentIds,
		arg.CreatedAt,
	)
	return err
}

const getInsightByEchoID = `-- name: GetInsightByEchoID :one
SELECT id, user_id, moment_id, echo_id, text, related_moment_ids, created_at
FROM insights WHERE echo_id = $1
`

func (q *Queries) GetInsightByEchoID(ctx context.Context, echoID pgtype.UUID) (Insight, error) {
	row := q.db.QueryRow(ctx, getInsightByEchoID, echoID)
	var i Insight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MomentID,
		&i.EchoID,
		&i.Text,
		&i.RelatedMomentIds,
		&i.CreatedAt,
	)
	return i, err
}

const getInsightByMomentID = `-- name: GetInsightByMomentID :one
SELECT id, user_id, moment_id, echo_id, text, related_moment_ids, created_at
FROM insights WHERE moment_id = $1
`

func (q *Queries) GetInsightByMomentID(ctx context.Context, momentID pgtype.UUID) (Insight, error) {
	row := q.db.QueryRow(ctx, getInsightByMomentID, momentID)
	var i Insight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MomentID,
		&i.EchoID,
		&i.Text,
		&i.RelatedMomentIds,
		&i.CreatedAt,
	)
	return i, err
}
