// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	SessionID         pgtype.UUID
	Role              string
	Content           string
	ReferencedMoments []byte
	CreatedAt         pgtype.Timestamptz
}

type ChatSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	StarID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Constellation struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Topic                string
	TopicEmbedding       []float32
	Name                 string
	ConstellationInsight string
	StarIds              []pgtype.UUID
	TopicPrompts         []string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Echo struct {
	ID               pgtype.UUID
	MomentID         pgtype.UUID
	UserID           pgtype.UUID
	MatchedMomentIds []pgtype.UUID
	Similarities     []float64
	CreatedAt        pgtype.Timestamptz
}

type Insight struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	MomentID         pgtype.UUID
	EchoID           pgtype.UUID
	Text             string
	RelatedMomentIds []pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

type Moment struct {
	ID         pgtype.UUID
	TraceID    pgtype.UUID
	UserID     pgtype.UUID
	Content    string
	Embeddings []byte
	CreatedAt  pgtype.Timestamptz
}

type Star struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TraceID   pgtype.UUID
	Topic     string
	CreatedAt pgtype.Timestamptz
}

type Trace struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Motivation string
	Stashed    bool
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Account      string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
