// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Moment struct {
	ID        pgtype.UUID
	TraceID   pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	Embedding pgvector.Vector
	Connected bool
	CreatedAt pgtype.Timestamptz
}

type Trace struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Topic     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Account      string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
