// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMomentsByUserID = `-- name: CountMomentsByUserID :one
SELECT COUNT(*) FROM moments WHERE user_id = $1
`

func (q *Queries) CountMomentsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMomentsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMoment = `-- name: CreateMoment :exec
INSERT INTO moments (id, trace_id, user_id, content, embeddings, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMomentParams struct {
	ID         pgtype.UUID
	TraceID    pgtype.UUID
	UserID     pgtype.UUID
	Content    string
	Embeddings []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateMoment(ctx context.Context, arg CreateMomentParams) error {
	_, err := q.db.Exec(ctx, createMoment,
		arg.ID,
		arg.TraceID,
		arg.UserID,
		arg.Content,
		arg.Embeddings,
		arg.CreatedAt,
	)
	return err
}

const firstMomentsByTraceIDs = `-- name: FirstMomentsByTraceIDs :many
SELECT DISTINCT ON (trace_id) id, trace_id, user_id, content, embeddings, created_at
FROM moments WHERE trace_id = ANY($1::UUID[]) ORDER BY trace_id, created_at ASC
`

func (q *Queries) FirstMomentsByTraceIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Moment, error) {
	rows, err := q.db.Query(ctx, firstMomentsByTraceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Moment
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.Content,
			&i.Embeddings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMomentByID = `-- name: GetMomentByID :one
SELECT id, trace_id, user_id, content, embeddings, created_at
FROM moments WHERE id = $1
`

func (q *Queries) GetMomentByID(ctx context.Context, id pgtype.UUID) (Moment, error) {
	row := q.db.QueryRow(ctx, getMomentByID, id)
	var i Moment
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.UserID,
		&i.Content,
		&i.Embeddings,
		&i.CreatedAt,
	)
	return i, err
}

const listMomentsByIDs = `-- name: ListMomentsByIDs :many
SELECT id, trace_id, user_id, content, embeddings, created_at
FROM moments WHERE id = ANY($1::UUID[])
`

func (q *Queries) ListMomentsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Moment, error) {
	rows, err := q.db.Query(ctx, listMomentsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Moment
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.Content,
			&i.Embeddings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentsByTraceID = `-- name: ListMomentsByTraceID :many
SELECT id, trace_id, user_id, content, embeddings, created_at
FROM moments WHERE trace_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListMomentsByTraceID(ctx context.Context, traceID pgtype.UUID) ([]Moment, error) {
	rows, err := q.db.Query(ctx, listMomentsByTraceID, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Moment
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.Content,
			&i.Embeddings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentsByUserID = `-- name: ListMomentsByUserID :many
SELECT id, trace_id, user_id, content, embeddings, created_at
FROM moments WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMomentsByUserID(ctx context.Context, userID pgtype.UUID) ([]Moment, error) {
	rows, err := q.db.Query(ctx, listMomentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Moment
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.Content,
			&i.Embeddings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentsByUserIDCursor = `-- name: ListMomentsByUserIDCursor :many
SELECT id, trace_id, user_id, content, embeddings, created_at
FROM moments
WHERE user_id = $1 AND created_at < $3::timestamptz
ORDER BY created_at DESC
LIMIT $2
`

type ListMomentsByUserIDCursorParams struct {
	UserID     pgtype.UUID
	Limit      int32
	CursorTime pgtype.Timestamptz
}

func (q *Queries) ListMomentsByUserIDCursor(ctx context.Context, arg ListMomentsByUserIDCursorParams) ([]Moment, error) {
	rows, err := q.db.Query(ctx, listMomentsByUserIDCursor, arg.UserID, arg.Limit, arg.CursorTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Moment
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.Content,
			&i.Embeddings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomMomentsByUserID = `-- name: RandomMomentsByUserID :many
SELECT id, trace_id, user_id, content, embeddings, created_at
FROM moments WHERE user_id = $1 ORDER BY random() LIMIT $2
`

type RandomMomentsByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) RandomMomentsByUserID(ctx context.Context, arg RandomMomentsByUserIDParams) ([]Moment, error) {
	rows, err := q.db.Query(ctx, randomMomentsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Moment
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.Content,
			&i.Embeddings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
