// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStar = `-- name: CreateStar :exec
INSERT INTO stars (id, user_id, trace_id, topic, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateStarParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TraceID   pgtype.UUID
	Topic     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateStar(ctx context.Context, arg CreateStarParams) error {
	_, err := q.db.Exec(ctx, createStar,
		arg.ID,
		arg.UserID,
		arg.TraceID,
		arg.Topic,
		arg.CreatedAt,
	)
	return err
}

const getStarByID = `-- name: GetStarByID :one
SELECT id, user_id, trace_id, topic, created_at
FROM stars WHERE id = $1
`

func (q *Queries) GetStarByID(ctx context.Context, id pgtype.UUID) (Star, error) {
	row := q.db.QueryRow(ctx, getStarByID, id)
	var i Star
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TraceID,
		&i.Topic,
		&i.CreatedAt,
	)
	return i, err
}

const getStarByTraceID = `-- name: GetStarByTraceID :one
SELECT id, user_id, trace_id, topic, created_at
FROM stars WHERE trace_id = $1
`

func (q *Queries) GetStarByTraceID(ctx context.Context, traceID pgtype.UUID) (Star, error) {
	row := q.db.QueryRow(ctx, getStarByTraceID, traceID)
	var i Star
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TraceID,
		&i.Topic,
		&i.CreatedAt,
	)
	return i, err
}

const listStarsByIDs = `-- name: ListStarsByIDs :many
SELECT id, user_id, trace_id, topic, created_at
FROM stars WHERE id = ANY($1::UUID[])
`

func (q *Queries) ListStarsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Star, error) {
	rows, err := q.db.Query(ctx, listStarsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Star
	for rows.Next() {
		var i Star
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TraceID,
			&i.Topic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
