// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrace = `-- name: CreateTrace :exec
INSERT INTO traces (id, user_id, topic, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTraceParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Topic     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) error {
	_, err := q.db.Exec(ctx, createTrace,
		arg.ID,
		arg.UserID,
		arg.Topic,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTrace = `-- name: DeleteTrace :exec
DELETE FROM traces WHERE id = $1
`

func (q *Queries) DeleteTrace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrace, id)
	return err
}

const getTraceByID = `-- name: GetTraceByID :one
SELECT id, user_id, topic, created_at, updated_at
FROM traces WHERE id = $1
`

func (q *Queries) GetTraceByID(ctx context.Context, id pgtype.UUID) (Trace, error) {
	row := q.db.QueryRow(ctx, getTraceByID, id)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrace = `-- name: UpdateTrace :exec
UPDATE traces SET topic = $2, updated_at = $3 WHERE id = $1
`

type UpdateTraceParams struct {
	ID        pgtype.UUID
	Topic     pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateTrace(ctx context.Context, arg UpdateTraceParams) error {
	_, err := q.db.Exec(ctx, updateTrace, arg.ID, arg.Topic, arg.UpdatedAt)
	return err
}
