// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: traces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrace = `-- name: CreateTrace :exec
INSERT INTO traces (id, user_id, motivation, stashed, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTraceParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Motivation string
	Stashed    bool
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) error {
	_, err := q.db.Exec(ctx, createTrace,
		arg.ID,
		arg.UserID,
		arg.Motivation,
		arg.Stashed,
		arg.CreatedAt,
	)
	return err
}

const deleteTrace = `-- name: DeleteTrace :exec
DELETE FROM traces WHERE id = $1
`

func (q *Queries) DeleteTrace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrace, id)
	return err
}

const getTraceByID = `-- name: GetTraceByID :one
SELECT id, user_id, motivation, stashed, created_at
FROM traces WHERE id = $1
`

func (q *Queries) GetTraceByID(ctx context.Context, id pgtype.UUID) (Trace, error) {
	row := q.db.QueryRow(ctx, getTraceByID, id)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Motivation,
		&i.Stashed,
		&i.CreatedAt,
	)
	return i, err
}

const listTracesByUserIDCursor = `-- name: ListTracesByUserIDCursor :many
SELECT id, user_id, motivation, stashed, created_at
FROM traces
WHERE user_id = $1 AND created_at < $3::timestamptz
ORDER BY created_at DESC
LIMIT $2
`

type ListTracesByUserIDCursorParams struct {
	UserID     pgtype.UUID
	Limit      int32
	CursorTime pgtype.Timestamptz
}

func (q *Queries) ListTracesByUserIDCursor(ctx context.Context, arg ListTracesByUserIDCursorParams) ([]Trace, error) {
	rows, err := q.db.Query(ctx, listTracesByUserIDCursor, arg.UserID, arg.Limit, arg.CursorTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trace
	for rows.Next() {
		var i Trace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Motivation,
			&i.Stashed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrace = `-- name: UpdateTrace :exec
UPDATE traces SET stashed = $2 WHERE id = $1
`

type UpdateTraceParams struct {
	ID      pgtype.UUID
	Stashed bool
}

func (q *Queries) UpdateTrace(ctx context.Context, arg UpdateTraceParams) error {
	_, err := q.db.Exec(ctx, updateTrace, arg.ID, arg.Stashed)
	return err
}
