// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, account, password_hash, created_at) VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Account      string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Account,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const getUserByAccount = `-- name: GetUserByAccount :one
SELECT id, password_hash FROM users WHERE account = $1
`

type GetUserByAccountRow struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) GetUserByAccount(ctx context.Context, account string) (GetUserByAccountRow, error) {
	row := q.db.QueryRow(ctx, getUserByAccount, account)
	var i GetUserByAccountRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}
