// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ego/api.proto

package ego

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StarVisualState int32

const (
	StarVisualState_STAR_VISUAL_STATE_UNSPECIFIED StarVisualState = 0
	StarVisualState_BRIGHT                        StarVisualState = 1 // 亮星（已成型星座成员）
	StarVisualState_PULSING                       StarVisualState = 2 // 弱光脉冲（正在成型）
	StarVisualState_DIM                           StarVisualState = 3 // 独立弱光（孤星）
)

// Enum value maps for StarVisualState.
var (
	StarVisualState_name = map[int32]string{
		0: "STAR_VISUAL_STATE_UNSPECIFIED",
		1: "BRIGHT",
		2: "PULSING",
		3: "DIM",
	}
	StarVisualState_value = map[string]int32{
		"STAR_VISUAL_STATE_UNSPECIFIED": 0,
		"BRIGHT":                        1,
		"PULSING":                       2,
		"DIM":                           3,
	}
)

func (x StarVisualState) Enum() *StarVisualState {
	p := new(StarVisualState)
	*p = x
	return p
}

func (x StarVisualState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StarVisualState) Descriptor() protoreflect.EnumDescriptor {
	return file_ego_api_proto_enumTypes[0].Descriptor()
}

func (StarVisualState) Type() protoreflect.EnumType {
	return &file_ego_api_proto_enumTypes[0]
}

func (x StarVisualState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StarVisualState.Descriptor instead.
func (StarVisualState) EnumDescriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{0}
}

type ConstellationStatus int32

const (
	ConstellationStatus_CONSTELLATION_STATUS_UNSPECIFIED ConstellationStatus = 0
	ConstellationStatus_FORMED                           ConstellationStatus = 1 // 已成型
	ConstellationStatus_FORMING                          ConstellationStatus = 2 // 正在成型
	ConstellationStatus_LONE                             ConstellationStatus = 3 // 孤星
)

// Enum value maps for ConstellationStatus.
var (
	ConstellationStatus_name = map[int32]string{
		0: "CONSTELLATION_STATUS_UNSPECIFIED",
		1: "FORMED",
		2: "FORMING",
		3: "LONE",
	}
	ConstellationStatus_value = map[string]int32{
		"CONSTELLATION_STATUS_UNSPECIFIED": 0,
		"FORMED":                           1,
		"FORMING":                          2,
		"LONE":                             3,
	}
)

func (x ConstellationStatus) Enum() *ConstellationStatus {
	p := new(ConstellationStatus)
	*p = x
	return p
}

func (x ConstellationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstellationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ego_api_proto_enumTypes[1].Descriptor()
}

func (ConstellationStatus) Type() protoreflect.EnumType {
	return &file_ego_api_proto_enumTypes[1]
}

func (x ConstellationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstellationStatus.Descriptor instead.
func (ConstellationStatus) EnumDescriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{1}
}

type ChatRole int32

const (
	ChatRole_CHAT_ROLE_UNSPECIFIED ChatRole = 0
	ChatRole_USER                  ChatRole = 1
	ChatRole_PAST_SELF             ChatRole = 2
)

// Enum value maps for ChatRole.
var (
	ChatRole_name = map[int32]string{
		0: "CHAT_ROLE_UNSPECIFIED",
		1: "USER",
		2: "PAST_SELF",
	}
	ChatRole_value = map[string]int32{
		"CHAT_ROLE_UNSPECIFIED": 0,
		"USER":                  1,
		"PAST_SELF":             2,
	}
)

func (x ChatRole) Enum() *ChatRole {
	p := new(ChatRole)
	*p = x
	return p
}

func (x ChatRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRole) Descriptor() protoreflect.EnumDescriptor {
	return file_ego_api_proto_enumTypes[2].Descriptor()
}

func (ChatRole) Type() protoreflect.EnumType {
	return &file_ego_api_proto_enumTypes[2]
}

func (x ChatRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRole.Descriptor instead.
func (ChatRole) EnumDescriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{2}
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_ego_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`      // JWT token，后续请求通过 metadata 传递
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // true = 本次自动注册
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_ego_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRes) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type Moment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                       // 用户写的原话
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix timestamp ms
	Connected     bool                   `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`                  // 是否已联结进星座
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`        // keywords/embedding 为服务端内部字段，不返回前端
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moment) Reset() {
	*x = Moment{}
	mi := &file_ego_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moment) ProtoMessage() {}

func (x *Moment) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moment.ProtoReflect.Descriptor instead.
func (*Moment) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{2}
}

func (x *Moment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Moment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Moment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Moment) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *Moment) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetMoment  *Moment                `protobuf:"bytes,2,opt,name=target_moment,json=targetMoment,proto3" json:"target_moment,omitempty"` // 匹配到的历史 Moment
	Candidates    []*Moment              `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`                         // 2-3 条候选回声
	Similarity    float32                `protobuf:"fixed32,4,opt,name=similarity,proto3" json:"similarity,omitempty"`                       // 相似度 0-1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_ego_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{3}
}

func (x *Echo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Echo) GetTargetMoment() *Moment {
	if x != nil {
		return x.TargetMoment
	}
	return nil
}

func (x *Echo) GetCandidates() []*Moment {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *Echo) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

type Insight struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text             string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"` // 第二人称观察文本
	RelatedMomentIds []string               `protobuf:"bytes,3,rep,name=related_moment_ids,json=relatedMomentIds,proto3" json:"related_moment_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Insight) Reset() {
	*x = Insight{}
	mi := &file_ego_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insight) ProtoMessage() {}

func (x *Insight) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insight.ProtoReflect.Descriptor instead.
func (*Insight) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{4}
}

func (x *Insight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Insight) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Insight) GetRelatedMomentIds() []string {
	if x != nil {
		return x.RelatedMomentIds
	}
	return nil
}

type Star struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"` // 星图坐标 x（0-1 归一化）
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"` // 星图坐标 y（0-1 归一化）
	VisualState   StarVisualState        `protobuf:"varint,5,opt,name=visual_state,json=visualState,proto3,enum=ego.StarVisualState" json:"visual_state,omitempty"`
	Rhythm        float32                `protobuf:"fixed32,6,opt,name=rhythm,proto3" json:"rhythm,omitempty"` // 闪烁节奏 0-1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Star) Reset() {
	*x = Star{}
	mi := &file_ego_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Star) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Star) ProtoMessage() {}

func (x *Star) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Star.ProtoReflect.Descriptor instead.
func (*Star) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{5}
}

func (x *Star) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Star) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Star) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Star) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Star) GetVisualState() StarVisualState {
	if x != nil {
		return x.VisualState
	}
	return StarVisualState_STAR_VISUAL_STATE_UNSPECIFIED
}

func (x *Star) GetRhythm() float32 {
	if x != nil {
		return x.Rhythm
	}
	return 0
}

type Constellation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 主题标签名
	Status        ConstellationStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=ego.ConstellationStatus" json:"status,omitempty"`
	Stars         []*Star                `protobuf:"bytes,4,rep,name=stars,proto3" json:"stars,omitempty"`
	MomentCount   int32                  `protobuf:"varint,5,opt,name=moment_count,json=momentCount,proto3" json:"moment_count,omitempty"` // 包含的话语数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constellation) Reset() {
	*x = Constellation{}
	mi := &file_ego_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constellation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constellation) ProtoMessage() {}

func (x *Constellation) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constellation.ProtoReflect.Descriptor instead.
func (*Constellation) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{6}
}

func (x *Constellation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Constellation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Constellation) GetStatus() ConstellationStatus {
	if x != nil {
		return x.Status
	}
	return ConstellationStatus_CONSTELLATION_STATUS_UNSPECIFIED
}

func (x *Constellation) GetStars() []*Star {
	if x != nil {
		return x.Stars
	}
	return nil
}

func (x *Constellation) GetMomentCount() int32 {
	if x != nil {
		return x.MomentCount
	}
	return 0
}

type TopicPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AnchorMoment  *Moment                `protobuf:"bytes,2,opt,name=anchor_moment,json=anchorMoment,proto3" json:"anchor_moment,omitempty"` // 锚定的原话
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`                             // 具体问题
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPrompt) Reset() {
	*x = TopicPrompt{}
	mi := &file_ego_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPrompt) ProtoMessage() {}

func (x *TopicPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPrompt.ProtoReflect.Descriptor instead.
func (*TopicPrompt) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{7}
}

func (x *TopicPrompt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopicPrompt) GetAnchorMoment() *Moment {
	if x != nil {
		return x.AnchorMoment
	}
	return nil
}

func (x *TopicPrompt) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          ChatRole               `protobuf:"varint,2,opt,name=role,proto3,enum=ego.ChatRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Referenced    []*MomentReference     `protobuf:"bytes,4,rep,name=referenced,proto3" json:"referenced,omitempty"` // 标注引用来源
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_ego_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetRole() ChatRole {
	if x != nil {
		return x.Role
	}
	return ChatRole_CHAT_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetReferenced() []*MomentReference {
	if x != nil {
		return x.Referenced
	}
	return nil
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MomentReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`       // "X月X日"
	Snippet       string                 `protobuf:"bytes,2,opt,name=snippet,proto3" json:"snippet,omitempty"` // 原话片段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MomentReference) Reset() {
	*x = MomentReference{}
	mi := &file_ego_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MomentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MomentReference) ProtoMessage() {}

func (x *MomentReference) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MomentReference.ProtoReflect.Descriptor instead.
func (*MomentReference) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{9}
}

func (x *MomentReference) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MomentReference) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type CreateMomentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 可选，延续已有的 Trace（"顺着再想想"场景）
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`                    // 可选，来自话题引子
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMomentReq) Reset() {
	*x = CreateMomentReq{}
	mi := &file_ego_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMomentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMomentReq) ProtoMessage() {}

func (x *CreateMomentReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMomentReq.ProtoReflect.Descriptor instead.
func (*CreateMomentReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{10}
}

func (x *CreateMomentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMomentReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateMomentReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type CreateMomentRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moment        *Moment                `protobuf:"bytes,1,opt,name=moment,proto3" json:"moment,omitempty"` // 已保存的 Moment
	Echo          *Echo                  `protobuf:"bytes,2,opt,name=echo,proto3" json:"echo,omitempty"`     // 匹配到的回声（含候选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMomentRes) Reset() {
	*x = CreateMomentRes{}
	mi := &file_ego_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMomentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMomentRes) ProtoMessage() {}

func (x *CreateMomentRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMomentRes.ProtoReflect.Descriptor instead.
func (*CreateMomentRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMomentRes) GetMoment() *Moment {
	if x != nil {
		return x.Moment
	}
	return nil
}

func (x *CreateMomentRes) GetEcho() *Echo {
	if x != nil {
		return x.Echo
	}
	return nil
}

type ListMomentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // 游标（上一页最后一条的 id），首次请求为空
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMomentsReq) Reset() {
	*x = ListMomentsReq{}
	mi := &file_ego_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMomentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMomentsReq) ProtoMessage() {}

func (x *ListMomentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMomentsReq.ProtoReflect.Descriptor instead.
func (*ListMomentsReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListMomentsReq) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMomentsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMomentsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moments       []*Moment              `protobuf:"bytes,1,rep,name=moments,proto3" json:"moments,omitempty"`                         // 扁平列表，前端按 created_at 自行按月分组
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 下一页游标，为空表示到底
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMomentsRes) Reset() {
	*x = ListMomentsRes{}
	mi := &file_ego_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMomentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMomentsRes) ProtoMessage() {}

func (x *ListMomentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMomentsRes.ProtoReflect.Descriptor instead.
func (*ListMomentsRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{13}
}

func (x *ListMomentsRes) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

func (x *ListMomentsRes) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListMomentsRes) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetRandomMomentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 获取数量，默认 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomMomentsReq) Reset() {
	*x = GetRandomMomentsReq{}
	mi := &file_ego_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomMomentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomMomentsReq) ProtoMessage() {}

func (x *GetRandomMomentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomMomentsReq.ProtoReflect.Descriptor instead.
func (*GetRandomMomentsReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetRandomMomentsReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRandomMomentsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moments       []*Moment              `protobuf:"bytes,1,rep,name=moments,proto3" json:"moments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomMomentsRes) Reset() {
	*x = GetRandomMomentsRes{}
	mi := &file_ego_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomMomentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomMomentsRes) ProtoMessage() {}

func (x *GetRandomMomentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomMomentsRes.ProtoReflect.Descriptor instead.
func (*GetRandomMomentsRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetRandomMomentsRes) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

type GenerateInsightReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentContent string                 `protobuf:"bytes,1,opt,name=current_content,json=currentContent,proto3" json:"current_content,omitempty"` // 用户刚写的话
	EchoMomentId   string                 `protobuf:"bytes,2,opt,name=echo_moment_id,json=echoMomentId,proto3" json:"echo_moment_id,omitempty"`     // 匹配到的回声 Moment id
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateInsightReq) Reset() {
	*x = GenerateInsightReq{}
	mi := &file_ego_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInsightReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInsightReq) ProtoMessage() {}

func (x *GenerateInsightReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInsightReq.ProtoReflect.Descriptor instead.
func (*GenerateInsightReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateInsightReq) GetCurrentContent() string {
	if x != nil {
		return x.CurrentContent
	}
	return ""
}

func (x *GenerateInsightReq) GetEchoMomentId() string {
	if x != nil {
		return x.EchoMomentId
	}
	return ""
}

type GenerateInsightRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insight       *Insight               `protobuf:"bytes,1,opt,name=insight,proto3" json:"insight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInsightRes) Reset() {
	*x = GenerateInsightRes{}
	mi := &file_ego_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInsightRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInsightRes) ProtoMessage() {}

func (x *GenerateInsightRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInsightRes.ProtoReflect.Descriptor instead.
func (*GenerateInsightRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateInsightRes) GetInsight() *Insight {
	if x != nil {
		return x.Insight
	}
	return nil
}

type StashTraceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 要寄存的 Trace id
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`                          // 星图坐标 x（0-1，前端根据星图可用区域分配）
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`                          // 星图坐标 y
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StashTraceReq) Reset() {
	*x = StashTraceReq{}
	mi := &file_ego_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StashTraceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StashTraceReq) ProtoMessage() {}

func (x *StashTraceReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StashTraceReq.ProtoReflect.Descriptor instead.
func (*StashTraceReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{18}
}

func (x *StashTraceReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StashTraceReq) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *StashTraceReq) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type StashTraceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Star          *Star                  `protobuf:"bytes,1,opt,name=star,proto3" json:"star,omitempty"` // 新生成的星星
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StashTraceRes) Reset() {
	*x = StashTraceRes{}
	mi := &file_ego_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StashTraceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StashTraceRes) ProtoMessage() {}

func (x *StashTraceRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StashTraceRes.ProtoReflect.Descriptor instead.
func (*StashTraceRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{19}
}

func (x *StashTraceRes) GetStar() *Star {
	if x != nil {
		return x.Star
	}
	return nil
}

type ListConstellationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConstellationsReq) Reset() {
	*x = ListConstellationsReq{}
	mi := &file_ego_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConstellationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConstellationsReq) ProtoMessage() {}

func (x *ListConstellationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConstellationsReq.ProtoReflect.Descriptor instead.
func (*ListConstellationsReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{20}
}

type ListConstellationsRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Constellations []*Constellation       `protobuf:"bytes,1,rep,name=constellations,proto3" json:"constellations,omitempty"`
	TotalStarCount int32                  `protobuf:"varint,2,opt,name=total_star_count,json=totalStarCount,proto3" json:"total_star_count,omitempty"` // 用于星图空状态："已有 N 颗星"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConstellationsRes) Reset() {
	*x = ListConstellationsRes{}
	mi := &file_ego_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConstellationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConstellationsRes) ProtoMessage() {}

func (x *ListConstellationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConstellationsRes.ProtoReflect.Descriptor instead.
func (*ListConstellationsRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{21}
}

func (x *ListConstellationsRes) GetConstellations() []*Constellation {
	if x != nil {
		return x.Constellations
	}
	return nil
}

func (x *ListConstellationsRes) GetTotalStarCount() int32 {
	if x != nil {
		return x.TotalStarCount
	}
	return 0
}

type GetConstellationReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConstellationId string                 `protobuf:"bytes,1,opt,name=constellation_id,json=constellationId,proto3" json:"constellation_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConstellationReq) Reset() {
	*x = GetConstellationReq{}
	mi := &file_ego_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConstellationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConstellationReq) ProtoMessage() {}

func (x *GetConstellationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConstellationReq.ProtoReflect.Descriptor instead.
func (*GetConstellationReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{22}
}

func (x *GetConstellationReq) GetConstellationId() string {
	if x != nil {
		return x.ConstellationId
	}
	return ""
}

type GetConstellationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constellation *Constellation         `protobuf:"bytes,1,opt,name=constellation,proto3" json:"constellation,omitempty"`
	Insight       *Insight               `protobuf:"bytes,2,opt,name=insight,proto3" json:"insight,omitempty"`                                    // ① ✦ 我发现
	Moments       []*Moment              `protobuf:"bytes,3,rep,name=moments,proto3" json:"moments,omitempty"`                                    // ② 主题里说过的话（全部原话列表）
	PastSelfCards []*PastSelfCard        `protobuf:"bytes,4,rep,name=past_self_cards,json=pastSelfCards,proto3" json:"past_self_cards,omitempty"` // ③ 和那时的自己说说话卡片
	TopicPrompts  []*TopicPrompt         `protobuf:"bytes,5,rep,name=topic_prompts,json=topicPrompts,proto3" json:"topic_prompts,omitempty"`      // ④ ✦ 我想和你聊聊
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConstellationRes) Reset() {
	*x = GetConstellationRes{}
	mi := &file_ego_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConstellationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConstellationRes) ProtoMessage() {}

func (x *GetConstellationRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConstellationRes.ProtoReflect.Descriptor instead.
func (*GetConstellationRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{23}
}

func (x *GetConstellationRes) GetConstellation() *Constellation {
	if x != nil {
		return x.Constellation
	}
	return nil
}

func (x *GetConstellationRes) GetInsight() *Insight {
	if x != nil {
		return x.Insight
	}
	return nil
}

func (x *GetConstellationRes) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

func (x *GetConstellationRes) GetPastSelfCards() []*PastSelfCard {
	if x != nil {
		return x.PastSelfCards
	}
	return nil
}

func (x *GetConstellationRes) GetTopicPrompts() []*TopicPrompt {
	if x != nil {
		return x.TopicPrompts
	}
	return nil
}

// 对话入口卡片
type PastSelfCard struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                         // 展示标题（如日期范围 "2月-3月"）
	OpeningLine    string                 `protobuf:"bytes,3,opt,name=opening_line,json=openingLine,proto3" json:"opening_line,omitempty"`          // AI 扮演时的开场白
	ContextMoments []*Moment              `protobuf:"bytes,4,rep,name=context_moments,json=contextMoments,proto3" json:"context_moments,omitempty"` // 该时段关联的原话
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PastSelfCard) Reset() {
	*x = PastSelfCard{}
	mi := &file_ego_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PastSelfCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastSelfCard) ProtoMessage() {}

func (x *PastSelfCard) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastSelfCard.ProtoReflect.Descriptor instead.
func (*PastSelfCard) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{24}
}

func (x *PastSelfCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PastSelfCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PastSelfCard) GetOpeningLine() string {
	if x != nil {
		return x.OpeningLine
	}
	return ""
}

func (x *PastSelfCard) GetContextMoments() []*Moment {
	if x != nil {
		return x.ContextMoments
	}
	return nil
}

type StartChatReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PastSelfCardId   string                 `protobuf:"bytes,1,opt,name=past_self_card_id,json=pastSelfCardId,proto3" json:"past_self_card_id,omitempty"`
	ContextMomentIds []string               `protobuf:"bytes,2,rep,name=context_moment_ids,json=contextMomentIds,proto3" json:"context_moment_ids,omitempty"` // 上下文原话 id 列表
	ChatSessionId    string                 `protobuf:"bytes,3,opt,name=chat_session_id,json=chatSessionId,proto3" json:"chat_session_id,omitempty"`          // 可选，传入旧 session_id 恢复对话
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartChatReq) Reset() {
	*x = StartChatReq{}
	mi := &file_ego_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatReq) ProtoMessage() {}

func (x *StartChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatReq.ProtoReflect.Descriptor instead.
func (*StartChatReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{25}
}

func (x *StartChatReq) GetPastSelfCardId() string {
	if x != nil {
		return x.PastSelfCardId
	}
	return ""
}

func (x *StartChatReq) GetContextMomentIds() []string {
	if x != nil {
		return x.ContextMomentIds
	}
	return nil
}

func (x *StartChatReq) GetChatSessionId() string {
	if x != nil {
		return x.ChatSessionId
	}
	return ""
}

type StartChatRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatSessionId string                 `protobuf:"bytes,1,opt,name=chat_session_id,json=chatSessionId,proto3" json:"chat_session_id,omitempty"` // 后续 SendMessage 带上此 id
	Opening       *ChatMessage           `protobuf:"bytes,2,opt,name=opening,proto3" json:"opening,omitempty"`                                    // AI 开场白（新建时）或最后一条 AI 消息（恢复时）
	History       []*ChatMessage         `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`                                    // 恢复时返回历史消息，新建时为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartChatRes) Reset() {
	*x = StartChatRes{}
	mi := &file_ego_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatRes) ProtoMessage() {}

func (x *StartChatRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatRes.ProtoReflect.Descriptor instead.
func (*StartChatRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{26}
}

func (x *StartChatRes) GetChatSessionId() string {
	if x != nil {
		return x.ChatSessionId
	}
	return ""
}

func (x *StartChatRes) GetOpening() *ChatMessage {
	if x != nil {
		return x.Opening
	}
	return nil
}

func (x *StartChatRes) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatSessionId string                 `protobuf:"bytes,1,opt,name=chat_session_id,json=chatSessionId,proto3" json:"chat_session_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 用户发送的内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_ego_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{27}
}

func (x *SendMessageReq) GetChatSessionId() string {
	if x != nil {
		return x.ChatSessionId
	}
	return ""
}

func (x *SendMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         *ChatMessage           `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"` // AI（past-self）回复
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRes) Reset() {
	*x = SendMessageRes{}
	mi := &file_ego_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRes) ProtoMessage() {}

func (x *SendMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRes.ProtoReflect.Descriptor instead.
func (*SendMessageRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{28}
}

func (x *SendMessageRes) GetReply() *ChatMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

var File_ego_api_proto protoreflect.FileDescriptor

const file_ego_api_proto_rawDesc = "" +
	"\n" +
	"\rego/api.proto\x12\x03ego\"@\n" +
	"\bLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\bLoginRes\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"\x8a\x01\n" +
	"\x06Moment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tconnected\x18\x04 \x01(\bR\tconnected\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"\x95\x01\n" +
	"\x04Echo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\rtarget_moment\x18\x02 \x01(\v2\v.ego.MomentR\ftargetMoment\x12+\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\v.ego.MomentR\n" +
	"candidates\x12\x1e\n" +
	"\n" +
	"similarity\x18\x04 \x01(\x02R\n" +
	"similarity\"[\n" +
	"\aInsight\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12,\n" +
	"\x12related_moment_ids\x18\x03 \x03(\tR\x10relatedMomentIds\"\x9e\x01\n" +
	"\x04Star\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x127\n" +
	"\fvisual_state\x18\x05 \x01(\x0e2\x14.ego.StarVisualStateR\vvisualState\x12\x16\n" +
	"\x06rhythm\x18\x06 \x01(\x02R\x06rhythm\"\xa9\x01\n" +
	"\rConstellation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.ego.ConstellationStatusR\x06status\x12\x1f\n" +
	"\x05stars\x18\x04 \x03(\v2\t.ego.StarR\x05stars\x12!\n" +
	"\fmoment_count\x18\x05 \x01(\x05R\vmomentCount\"k\n" +
	"\vTopicPrompt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\ranchor_moment\x18\x02 \x01(\v2\v.ego.MomentR\fanchorMoment\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\"\xae\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04role\x18\x02 \x01(\x0e2\r.ego.ChatRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x124\n" +
	"\n" +
	"referenced\x18\x04 \x03(\v2\x14.ego.MomentReferenceR\n" +
	"referenced\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"?\n" +
	"\x0fMomentReference\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x18\n" +
	"\asnippet\x18\x02 \x01(\tR\asnippet\"\\\n" +
	"\x0fCreateMomentReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"U\n" +
	"\x0fCreateMomentRes\x12#\n" +
	"\x06moment\x18\x01 \x01(\v2\v.ego.MomentR\x06moment\x12\x1d\n" +
	"\x04echo\x18\x02 \x01(\v2\t.ego.EchoR\x04echo\"E\n" +
	"\x0eListMomentsReq\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"s\n" +
	"\x0eListMomentsRes\x12%\n" +
	"\amoments\x18\x01 \x03(\v2\v.ego.MomentR\amoments\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"+\n" +
	"\x13GetRandomMomentsReq\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"<\n" +
	"\x13GetRandomMomentsRes\x12%\n" +
	"\amoments\x18\x01 \x03(\v2\v.ego.MomentR\amoments\"c\n" +
	"\x12GenerateInsightReq\x12'\n" +
	"\x0fcurrent_content\x18\x01 \x01(\tR\x0ecurrentContent\x12$\n" +
	"\x0eecho_moment_id\x18\x02 \x01(\tR\fechoMomentId\"<\n" +
	"\x12GenerateInsightRes\x12&\n" +
	"\ainsight\x18\x01 \x01(\v2\f.ego.InsightR\ainsight\"F\n" +
	"\rStashTraceReq\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\".\n" +
	"\rStashTraceRes\x12\x1d\n" +
	"\x04star\x18\x01 \x01(\v2\t.ego.StarR\x04star\"\x17\n" +
	"\x15ListConstellationsReq\"}\n" +
	"\x15ListConstellationsRes\x12:\n" +
	"\x0econstellations\x18\x01 \x03(\v2\x12.ego.ConstellationR\x0econstellations\x12(\n" +
	"\x10total_star_count\x18\x02 \x01(\x05R\x0etotalStarCount\"@\n" +
	"\x13GetConstellationReq\x12)\n" +
	"\x10constellation_id\x18\x01 \x01(\tR\x0fconstellationId\"\x90\x02\n" +
	"\x13GetConstellationRes\x128\n" +
	"\rconstellation\x18\x01 \x01(\v2\x12.ego.ConstellationR\rconstellation\x12&\n" +
	"\ainsight\x18\x02 \x01(\v2\f.ego.InsightR\ainsight\x12%\n" +
	"\amoments\x18\x03 \x03(\v2\v.ego.MomentR\amoments\x129\n" +
	"\x0fpast_self_cards\x18\x04 \x03(\v2\x11.ego.PastSelfCardR\rpastSelfCards\x125\n" +
	"\rtopic_prompts\x18\x05 \x03(\v2\x10.ego.TopicPromptR\ftopicPrompts\"\x8d\x01\n" +
	"\fPastSelfCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fopening_line\x18\x03 \x01(\tR\vopeningLine\x124\n" +
	"\x0fcontext_moments\x18\x04 \x03(\v2\v.ego.MomentR\x0econtextMoments\"\x8f\x01\n" +
	"\fStartChatReq\x12)\n" +
	"\x11past_self_card_id\x18\x01 \x01(\tR\x0epastSelfCardId\x12,\n" +
	"\x12context_moment_ids\x18\x02 \x03(\tR\x10contextMomentIds\x12&\n" +
	"\x0fchat_session_id\x18\x03 \x01(\tR\rchatSessionId\"\x8e\x01\n" +
	"\fStartChatRes\x12&\n" +
	"\x0fchat_session_id\x18\x01 \x01(\tR\rchatSessionId\x12*\n" +
	"\aopening\x18\x02 \x01(\v2\x10.ego.ChatMessageR\aopening\x12*\n" +
	"\ahistory\x18\x03 \x03(\v2\x10.ego.ChatMessageR\ahistory\"R\n" +
	"\x0eSendMessageReq\x12&\n" +
	"\x0fchat_session_id\x18\x01 \x01(\tR\rchatSessionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"8\n" +
	"\x0eSendMessageRes\x12&\n" +
	"\x05reply\x18\x01 \x01(\v2\x10.ego.ChatMessageR\x05reply*V\n" +
	"\x0fStarVisualState\x12!\n" +
	"\x1dSTAR_VISUAL_STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06BRIGHT\x10\x01\x12\v\n" +
	"\aPULSING\x10\x02\x12\a\n" +
	"\x03DIM\x10\x03*^\n" +
	"\x13ConstellationStatus\x12$\n" +
	" CONSTELLATION_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06FORMED\x10\x01\x12\v\n" +
	"\aFORMING\x10\x02\x12\b\n" +
	"\x04LONE\x10\x03*>\n" +
	"\bChatRole\x12\x19\n" +
	"\x15CHAT_ROLE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\r\n" +
	"\tPAST_SELF\x10\x022\xe6\x04\n" +
	"\x03Ego\x12%\n" +
	"\x05Login\x12\r.ego.LoginReq\x1a\r.ego.LoginRes\x12:\n" +
	"\fCreateMoment\x12\x14.ego.CreateMomentReq\x1a\x14.ego.CreateMomentRes\x127\n" +
	"\vListMoments\x12\x13.ego.ListMomentsReq\x1a\x13.ego.ListMomentsRes\x12F\n" +
	"\x10GetRandomMoments\x12\x18.ego.GetRandomMomentsReq\x1a\x18.ego.GetRandomMomentsRes\x12C\n" +
	"\x0fGenerateInsight\x12\x17.ego.GenerateInsightReq\x1a\x17.ego.GenerateInsightRes\x124\n" +
	"\n" +
	"StashTrace\x12\x12.ego.StashTraceReq\x1a\x12.ego.StashTraceRes\x12L\n" +
	"\x12ListConstellations\x12\x1a.ego.ListConstellationsReq\x1a\x1a.ego.ListConstellationsRes\x12F\n" +
	"\x10GetConstellation\x12\x18.ego.GetConstellationReq\x1a\x18.ego.GetConstellationRes\x121\n" +
	"\tStartChat\x12\x11.ego.StartChatReq\x1a\x11.ego.StartChatRes\x127\n" +
	"\vSendMessage\x12\x13.ego.SendMessageReq\x1a\x13.ego.SendMessageResB\x16Z\x14ego-server/proto/egob\x06proto3"

var (
	file_ego_api_proto_rawDescOnce sync.Once
	file_ego_api_proto_rawDescData []byte
)

func file_ego_api_proto_rawDescGZIP() []byte {
	file_ego_api_proto_rawDescOnce.Do(func() {
		file_ego_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ego_api_proto_rawDesc), len(file_ego_api_proto_rawDesc)))
	})
	return file_ego_api_proto_rawDescData
}

var file_ego_api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ego_api_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ego_api_proto_goTypes = []any{
	(StarVisualState)(0),          // 0: ego.StarVisualState
	(ConstellationStatus)(0),      // 1: ego.ConstellationStatus
	(ChatRole)(0),                 // 2: ego.ChatRole
	(*LoginReq)(nil),              // 3: ego.LoginReq
	(*LoginRes)(nil),              // 4: ego.LoginRes
	(*Moment)(nil),                // 5: ego.Moment
	(*Echo)(nil),                  // 6: ego.Echo
	(*Insight)(nil),               // 7: ego.Insight
	(*Star)(nil),                  // 8: ego.Star
	(*Constellation)(nil),         // 9: ego.Constellation
	(*TopicPrompt)(nil),           // 10: ego.TopicPrompt
	(*ChatMessage)(nil),           // 11: ego.ChatMessage
	(*MomentReference)(nil),       // 12: ego.MomentReference
	(*CreateMomentReq)(nil),       // 13: ego.CreateMomentReq
	(*CreateMomentRes)(nil),       // 14: ego.CreateMomentRes
	(*ListMomentsReq)(nil),        // 15: ego.ListMomentsReq
	(*ListMomentsRes)(nil),        // 16: ego.ListMomentsRes
	(*GetRandomMomentsReq)(nil),   // 17: ego.GetRandomMomentsReq
	(*GetRandomMomentsRes)(nil),   // 18: ego.GetRandomMomentsRes
	(*GenerateInsightReq)(nil),    // 19: ego.GenerateInsightReq
	(*GenerateInsightRes)(nil),    // 20: ego.GenerateInsightRes
	(*StashTraceReq)(nil),         // 21: ego.StashTraceReq
	(*StashTraceRes)(nil),         // 22: ego.StashTraceRes
	(*ListConstellationsReq)(nil), // 23: ego.ListConstellationsReq
	(*ListConstellationsRes)(nil), // 24: ego.ListConstellationsRes
	(*GetConstellationReq)(nil),   // 25: ego.GetConstellationReq
	(*GetConstellationRes)(nil),   // 26: ego.GetConstellationRes
	(*PastSelfCard)(nil),          // 27: ego.PastSelfCard
	(*StartChatReq)(nil),          // 28: ego.StartChatReq
	(*StartChatRes)(nil),          // 29: ego.StartChatRes
	(*SendMessageReq)(nil),        // 30: ego.SendMessageReq
	(*SendMessageRes)(nil),        // 31: ego.SendMessageRes
}
var file_ego_api_proto_depIdxs = []int32{
	5,  // 0: ego.Echo.target_moment:type_name -> ego.Moment
	5,  // 1: ego.Echo.candidates:type_name -> ego.Moment
	0,  // 2: ego.Star.visual_state:type_name -> ego.StarVisualState
	1,  // 3: ego.Constellation.status:type_name -> ego.ConstellationStatus
	8,  // 4: ego.Constellation.stars:type_name -> ego.Star
	5,  // 5: ego.TopicPrompt.anchor_moment:type_name -> ego.Moment
	2,  // 6: ego.ChatMessage.role:type_name -> ego.ChatRole
	12, // 7: ego.ChatMessage.referenced:type_name -> ego.MomentReference
	5,  // 8: ego.CreateMomentRes.moment:type_name -> ego.Moment
	6,  // 9: ego.CreateMomentRes.echo:type_name -> ego.Echo
	5,  // 10: ego.ListMomentsRes.moments:type_name -> ego.Moment
	5,  // 11: ego.GetRandomMomentsRes.moments:type_name -> ego.Moment
	7,  // 12: ego.GenerateInsightRes.insight:type_name -> ego.Insight
	8,  // 13: ego.StashTraceRes.star:type_name -> ego.Star
	9,  // 14: ego.ListConstellationsRes.constellations:type_name -> ego.Constellation
	9,  // 15: ego.GetConstellationRes.constellation:type_name -> ego.Constellation
	7,  // 16: ego.GetConstellationRes.insight:type_name -> ego.Insight
	5,  // 17: ego.GetConstellationRes.moments:type_name -> ego.Moment
	27, // 18: ego.GetConstellationRes.past_self_cards:type_name -> ego.PastSelfCard
	10, // 19: ego.GetConstellationRes.topic_prompts:type_name -> ego.TopicPrompt
	5,  // 20: ego.PastSelfCard.context_moments:type_name -> ego.Moment
	11, // 21: ego.StartChatRes.opening:type_name -> ego.ChatMessage
	11, // 22: ego.StartChatRes.history:type_name -> ego.ChatMessage
	11, // 23: ego.SendMessageRes.reply:type_name -> ego.ChatMessage
	3,  // 24: ego.Ego.Login:input_type -> ego.LoginReq
	13, // 25: ego.Ego.CreateMoment:input_type -> ego.CreateMomentReq
	15, // 26: ego.Ego.ListMoments:input_type -> ego.ListMomentsReq
	17, // 27: ego.Ego.GetRandomMoments:input_type -> ego.GetRandomMomentsReq
	19, // 28: ego.Ego.GenerateInsight:input_type -> ego.GenerateInsightReq
	21, // 29: ego.Ego.StashTrace:input_type -> ego.StashTraceReq
	23, // 30: ego.Ego.ListConstellations:input_type -> ego.ListConstellationsReq
	25, // 31: ego.Ego.GetConstellation:input_type -> ego.GetConstellationReq
	28, // 32: ego.Ego.StartChat:input_type -> ego.StartChatReq
	30, // 33: ego.Ego.SendMessage:input_type -> ego.SendMessageReq
	4,  // 34: ego.Ego.Login:output_type -> ego.LoginRes
	14, // 35: ego.Ego.CreateMoment:output_type -> ego.CreateMomentRes
	16, // 36: ego.Ego.ListMoments:output_type -> ego.ListMomentsRes
	18, // 37: ego.Ego.GetRandomMoments:output_type -> ego.GetRandomMomentsRes
	20, // 38: ego.Ego.GenerateInsight:output_type -> ego.GenerateInsightRes
	22, // 39: ego.Ego.StashTrace:output_type -> ego.StashTraceRes
	24, // 40: ego.Ego.ListConstellations:output_type -> ego.ListConstellationsRes
	26, // 41: ego.Ego.GetConstellation:output_type -> ego.GetConstellationRes
	29, // 42: ego.Ego.StartChat:output_type -> ego.StartChatRes
	31, // 43: ego.Ego.SendMessage:output_type -> ego.SendMessageRes
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_ego_api_proto_init() }
func file_ego_api_proto_init() {
	if File_ego_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ego_api_proto_rawDesc), len(file_ego_api_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ego_api_proto_goTypes,
		DependencyIndexes: file_ego_api_proto_depIdxs,
		EnumInfos:         file_ego_api_proto_enumTypes,
		MessageInfos:      file_ego_api_proto_msgTypes,
	}.Build()
	File_ego_api_proto = out.File
	file_ego_api_proto_goTypes = nil
	file_ego_api_proto_depIdxs = nil
}
