// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: ego/api.proto

package ego

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRole int32

const (
	ChatRole_CHAT_ROLE_UNSPECIFIED ChatRole = 0
	ChatRole_USER                  ChatRole = 1
	ChatRole_PAST_SELF             ChatRole = 2
)

// Enum value maps for ChatRole.
var (
	ChatRole_name = map[int32]string{
		0: "CHAT_ROLE_UNSPECIFIED",
		1: "USER",
		2: "PAST_SELF",
	}
	ChatRole_value = map[string]int32{
		"CHAT_ROLE_UNSPECIFIED": 0,
		"USER":                  1,
		"PAST_SELF":             2,
	}
)

func (x ChatRole) Enum() *ChatRole {
	p := new(ChatRole)
	*p = x
	return p
}

func (x ChatRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRole) Descriptor() protoreflect.EnumDescriptor {
	return file_ego_api_proto_enumTypes[0].Descriptor()
}

func (ChatRole) Type() protoreflect.EnumType {
	return &file_ego_api_proto_enumTypes[0]
}

func (x ChatRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRole.Descriptor instead.
func (ChatRole) EnumDescriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{0}
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_ego_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`      // JWT token，后续请求通过 metadata 传递
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // true = 本次自动注册
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_ego_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRes) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type Moment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 用户写的原话
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix timestamp ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moment) Reset() {
	*x = Moment{}
	mi := &file_ego_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moment) ProtoMessage() {}

func (x *Moment) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moment.ProtoReflect.Descriptor instead.
func (*Moment) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{2}
}

func (x *Moment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Moment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Moment) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Moment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Echo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MomentId         string                 `protobuf:"bytes,2,opt,name=moment_id,json=momentId,proto3" json:"moment_id,omitempty"`                           // 为哪个 Moment 匹配的
	MatchedMomentIds []string               `protobuf:"bytes,3,rep,name=matched_moment_ids,json=matchedMomentIds,proto3" json:"matched_moment_ids,omitempty"` // 匹配到的历史 Moment id 列表（按相似度降序）
	Similarities     []float32              `protobuf:"fixed32,4,rep,packed,name=similarities,proto3" json:"similarities,omitempty"`                          // 对应相似度，与 matched_moment_ids 一一对应
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_ego_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{3}
}

func (x *Echo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Echo) GetMomentId() string {
	if x != nil {
		return x.MomentId
	}
	return ""
}

func (x *Echo) GetMatchedMomentIds() []string {
	if x != nil {
		return x.MatchedMomentIds
	}
	return nil
}

func (x *Echo) GetSimilarities() []float32 {
	if x != nil {
		return x.Similarities
	}
	return nil
}

type Insight struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MomentId         string                 `protobuf:"bytes,2,opt,name=moment_id,json=momentId,proto3" json:"moment_id,omitempty"` // 为哪个 Moment 生成的观察
	EchoId           string                 `protobuf:"bytes,3,opt,name=echo_id,json=echoId,proto3" json:"echo_id,omitempty"`       // 基于哪个 Echo 生成
	Text             string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`                         // 第二人称观察文本
	RelatedMomentIds []string               `protobuf:"bytes,5,rep,name=related_moment_ids,json=relatedMomentIds,proto3" json:"related_moment_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Insight) Reset() {
	*x = Insight{}
	mi := &file_ego_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insight) ProtoMessage() {}

func (x *Insight) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insight.ProtoReflect.Descriptor instead.
func (*Insight) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{4}
}

func (x *Insight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Insight) GetMomentId() string {
	if x != nil {
		return x.MomentId
	}
	return ""
}

func (x *Insight) GetEchoId() string {
	if x != nil {
		return x.EchoId
	}
	return ""
}

func (x *Insight) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Insight) GetRelatedMomentIds() []string {
	if x != nil {
		return x.RelatedMomentIds
	}
	return nil
}

type Star struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 关联的 Trace
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`                    // AI 生成的主题文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Star) Reset() {
	*x = Star{}
	mi := &file_ego_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Star) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Star) ProtoMessage() {}

func (x *Star) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Star.ProtoReflect.Descriptor instead.
func (*Star) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{5}
}

func (x *Star) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Star) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Star) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type Constellation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                             // 主题标签名
	ConstellationInsight string                 `protobuf:"bytes,3,opt,name=constellation_insight,json=constellationInsight,proto3" json:"constellation_insight,omitempty"` // Constellation 级 AI 观察
	StarIds              []string               `protobuf:"bytes,4,rep,name=star_ids,json=starIds,proto3" json:"star_ids,omitempty"`                                        // 包含的 Star id 列表
	TopicPrompts         []string               `protobuf:"bytes,5,rep,name=topic_prompts,json=topicPrompts,proto3" json:"topic_prompts,omitempty"`                         // 话题引子列表
	StarCount            int32                  `protobuf:"varint,6,opt,name=star_count,json=starCount,proto3" json:"star_count,omitempty"`                                 // 包含的 Star 数量（方便前端判断状态）
	CreatedAt            int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Constellation) Reset() {
	*x = Constellation{}
	mi := &file_ego_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constellation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constellation) ProtoMessage() {}

func (x *Constellation) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constellation.ProtoReflect.Descriptor instead.
func (*Constellation) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{6}
}

func (x *Constellation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Constellation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Constellation) GetConstellationInsight() string {
	if x != nil {
		return x.ConstellationInsight
	}
	return ""
}

func (x *Constellation) GetStarIds() []string {
	if x != nil {
		return x.StarIds
	}
	return nil
}

func (x *Constellation) GetTopicPrompts() []string {
	if x != nil {
		return x.TopicPrompts
	}
	return nil
}

func (x *Constellation) GetStarCount() int32 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

func (x *Constellation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Constellation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          ChatRole               `protobuf:"varint,2,opt,name=role,proto3,enum=ego.ChatRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Referenced    []*MomentReference     `protobuf:"bytes,4,rep,name=referenced,proto3" json:"referenced,omitempty"` // 标注引用来源
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_ego_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetRole() ChatRole {
	if x != nil {
		return x.Role
	}
	return ChatRole_CHAT_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetReferenced() []*MomentReference {
	if x != nil {
		return x.Referenced
	}
	return nil
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MomentReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`       // "X月X日"
	Snippet       string                 `protobuf:"bytes,2,opt,name=snippet,proto3" json:"snippet,omitempty"` // 原话片段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MomentReference) Reset() {
	*x = MomentReference{}
	mi := &file_ego_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MomentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MomentReference) ProtoMessage() {}

func (x *MomentReference) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MomentReference.ProtoReflect.Descriptor instead.
func (*MomentReference) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{8}
}

func (x *MomentReference) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MomentReference) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type CreateMomentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 继续已有 Trace（"顺着再想想"场景），空则新建 Trace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMomentReq) Reset() {
	*x = CreateMomentReq{}
	mi := &file_ego_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMomentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMomentReq) ProtoMessage() {}

func (x *CreateMomentReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMomentReq.ProtoReflect.Descriptor instead.
func (*CreateMomentReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{9}
}

func (x *CreateMomentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMomentReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CreateMomentRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moment        *Moment                `protobuf:"bytes,1,opt,name=moment,proto3" json:"moment,omitempty"` // 已保存的 Moment
	Echo          *Echo                  `protobuf:"bytes,2,opt,name=echo,proto3" json:"echo,omitempty"`     // 匹配到的回声（含候选列表）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMomentRes) Reset() {
	*x = CreateMomentRes{}
	mi := &file_ego_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMomentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMomentRes) ProtoMessage() {}

func (x *CreateMomentRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMomentRes.ProtoReflect.Descriptor instead.
func (*CreateMomentRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{10}
}

func (x *CreateMomentRes) GetMoment() *Moment {
	if x != nil {
		return x.Moment
	}
	return nil
}

func (x *CreateMomentRes) GetEcho() *Echo {
	if x != nil {
		return x.Echo
	}
	return nil
}

type GetMomentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMomentsReq) Reset() {
	*x = GetMomentsReq{}
	mi := &file_ego_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMomentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentsReq) ProtoMessage() {}

func (x *GetMomentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentsReq.ProtoReflect.Descriptor instead.
func (*GetMomentsReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetMomentsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetMomentsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moments       []*Moment              `protobuf:"bytes,1,rep,name=moments,proto3" json:"moments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMomentsRes) Reset() {
	*x = GetMomentsRes{}
	mi := &file_ego_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMomentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentsRes) ProtoMessage() {}

func (x *GetMomentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentsRes.ProtoReflect.Descriptor instead.
func (*GetMomentsRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetMomentsRes) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

type GenerateInsightReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MomentId      string                 `protobuf:"bytes,1,opt,name=moment_id,json=momentId,proto3" json:"moment_id,omitempty"` // 基于哪个 Moment
	EchoId        string                 `protobuf:"bytes,2,opt,name=echo_id,json=echoId,proto3" json:"echo_id,omitempty"`       // 基于哪个 Echo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInsightReq) Reset() {
	*x = GenerateInsightReq{}
	mi := &file_ego_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInsightReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInsightReq) ProtoMessage() {}

func (x *GenerateInsightReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInsightReq.ProtoReflect.Descriptor instead.
func (*GenerateInsightReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateInsightReq) GetMomentId() string {
	if x != nil {
		return x.MomentId
	}
	return ""
}

func (x *GenerateInsightReq) GetEchoId() string {
	if x != nil {
		return x.EchoId
	}
	return ""
}

type GenerateInsightRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insight       *Insight               `protobuf:"bytes,1,opt,name=insight,proto3" json:"insight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInsightRes) Reset() {
	*x = GenerateInsightRes{}
	mi := &file_ego_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInsightRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInsightRes) ProtoMessage() {}

func (x *GenerateInsightRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInsightRes.ProtoReflect.Descriptor instead.
func (*GenerateInsightRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateInsightRes) GetInsight() *Insight {
	if x != nil {
		return x.Insight
	}
	return nil
}

type Trace struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Motivation         string                 `protobuf:"bytes,2,opt,name=motivation,proto3" json:"motivation,omitempty"` // 'direct' | 'trace:<id>' | 'constellation:<id>'
	Stashed            bool                   `protobuf:"varint,3,opt,name=stashed,proto3" json:"stashed,omitempty"`      // 是否已收进星图
	CreatedAt          int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FirstMomentContent string                 `protobuf:"bytes,5,opt,name=first_moment_content,json=firstMomentContent,proto3" json:"first_moment_content,omitempty"` // 第一条 Moment 的内容预览
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_ego_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{15}
}

func (x *Trace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trace) GetMotivation() string {
	if x != nil {
		return x.Motivation
	}
	return ""
}

func (x *Trace) GetStashed() bool {
	if x != nil {
		return x.Stashed
	}
	return false
}

func (x *Trace) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Trace) GetFirstMomentContent() string {
	if x != nil {
		return x.FirstMomentContent
	}
	return ""
}

type TraceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moment        *Moment                `protobuf:"bytes,1,opt,name=moment,proto3" json:"moment,omitempty"`
	Echos         []*Echo                `protobuf:"bytes,2,rep,name=echos,proto3" json:"echos,omitempty"`
	Insight       *Insight               `protobuf:"bytes,3,opt,name=insight,proto3" json:"insight,omitempty"` // 可能为空（尚未生成）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceItem) Reset() {
	*x = TraceItem{}
	mi := &file_ego_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceItem) ProtoMessage() {}

func (x *TraceItem) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceItem.ProtoReflect.Descriptor instead.
func (*TraceItem) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{16}
}

func (x *TraceItem) GetMoment() *Moment {
	if x != nil {
		return x.Moment
	}
	return nil
}

func (x *TraceItem) GetEchos() []*Echo {
	if x != nil {
		return x.Echos
	}
	return nil
}

func (x *TraceItem) GetInsight() *Insight {
	if x != nil {
		return x.Insight
	}
	return nil
}

type ListTracesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // 游标（上一页最后一条的 id），首次请求为空
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracesReq) Reset() {
	*x = ListTracesReq{}
	mi := &file_ego_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracesReq) ProtoMessage() {}

func (x *ListTracesReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracesReq.ProtoReflect.Descriptor instead.
func (*ListTracesReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{17}
}

func (x *ListTracesReq) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListTracesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTracesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*Trace               `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`                           // Trace 列表（不含 Item，轻量）
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 下一页游标，为空表示到底
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracesRes) Reset() {
	*x = ListTracesRes{}
	mi := &file_ego_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracesRes) ProtoMessage() {}

func (x *ListTracesRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracesRes.ProtoReflect.Descriptor instead.
func (*ListTracesRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{18}
}

func (x *ListTracesRes) GetTraces() []*Trace {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *ListTracesRes) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListTracesRes) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetTraceDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceDetailReq) Reset() {
	*x = GetTraceDetailReq{}
	mi := &file_ego_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceDetailReq) ProtoMessage() {}

func (x *GetTraceDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceDetailReq.ProtoReflect.Descriptor instead.
func (*GetTraceDetailReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{19}
}

func (x *GetTraceDetailReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetTraceDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         *Trace                 `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	Items         []*TraceItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"` // <Moment, Echo[], Insight>[]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceDetailRes) Reset() {
	*x = GetTraceDetailRes{}
	mi := &file_ego_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceDetailRes) ProtoMessage() {}

func (x *GetTraceDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceDetailRes.ProtoReflect.Descriptor instead.
func (*GetTraceDetailRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{20}
}

func (x *GetTraceDetailRes) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *GetTraceDetailRes) GetItems() []*TraceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRandomMomentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 获取数量，默认 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomMomentsReq) Reset() {
	*x = GetRandomMomentsReq{}
	mi := &file_ego_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomMomentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomMomentsReq) ProtoMessage() {}

func (x *GetRandomMomentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomMomentsReq.ProtoReflect.Descriptor instead.
func (*GetRandomMomentsReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{21}
}

func (x *GetRandomMomentsReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRandomMomentsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moments       []*Moment              `protobuf:"bytes,1,rep,name=moments,proto3" json:"moments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomMomentsRes) Reset() {
	*x = GetRandomMomentsRes{}
	mi := &file_ego_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomMomentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomMomentsRes) ProtoMessage() {}

func (x *GetRandomMomentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomMomentsRes.ProtoReflect.Descriptor instead.
func (*GetRandomMomentsRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{22}
}

func (x *GetRandomMomentsRes) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

type StashTraceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 要寄存的 Trace id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StashTraceReq) Reset() {
	*x = StashTraceReq{}
	mi := &file_ego_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StashTraceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StashTraceReq) ProtoMessage() {}

func (x *StashTraceReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StashTraceReq.ProtoReflect.Descriptor instead.
func (*StashTraceReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{23}
}

func (x *StashTraceReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type StashTraceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Star          *Star                  `protobuf:"bytes,1,opt,name=star,proto3" json:"star,omitempty"` // 新生成的 Star
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StashTraceRes) Reset() {
	*x = StashTraceRes{}
	mi := &file_ego_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StashTraceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StashTraceRes) ProtoMessage() {}

func (x *StashTraceRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StashTraceRes.ProtoReflect.Descriptor instead.
func (*StashTraceRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{24}
}

func (x *StashTraceRes) GetStar() *Star {
	if x != nil {
		return x.Star
	}
	return nil
}

type ListConstellationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConstellationsReq) Reset() {
	*x = ListConstellationsReq{}
	mi := &file_ego_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConstellationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConstellationsReq) ProtoMessage() {}

func (x *ListConstellationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConstellationsReq.ProtoReflect.Descriptor instead.
func (*ListConstellationsReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{25}
}

type ListConstellationsRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Constellations []*Constellation       `protobuf:"bytes,1,rep,name=constellations,proto3" json:"constellations,omitempty"`
	TotalStarCount int32                  `protobuf:"varint,2,opt,name=total_star_count,json=totalStarCount,proto3" json:"total_star_count,omitempty"` // 用于星图空状态："已有 N 颗星"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConstellationsRes) Reset() {
	*x = ListConstellationsRes{}
	mi := &file_ego_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConstellationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConstellationsRes) ProtoMessage() {}

func (x *ListConstellationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConstellationsRes.ProtoReflect.Descriptor instead.
func (*ListConstellationsRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{26}
}

func (x *ListConstellationsRes) GetConstellations() []*Constellation {
	if x != nil {
		return x.Constellations
	}
	return nil
}

func (x *ListConstellationsRes) GetTotalStarCount() int32 {
	if x != nil {
		return x.TotalStarCount
	}
	return 0
}

type GetConstellationReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConstellationId string                 `protobuf:"bytes,1,opt,name=constellation_id,json=constellationId,proto3" json:"constellation_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConstellationReq) Reset() {
	*x = GetConstellationReq{}
	mi := &file_ego_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConstellationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConstellationReq) ProtoMessage() {}

func (x *GetConstellationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConstellationReq.ProtoReflect.Descriptor instead.
func (*GetConstellationReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{27}
}

func (x *GetConstellationReq) GetConstellationId() string {
	if x != nil {
		return x.ConstellationId
	}
	return ""
}

type GetConstellationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constellation *Constellation         `protobuf:"bytes,1,opt,name=constellation,proto3" json:"constellation,omitempty"`
	// ① ✦ 我发现（constellation_insight 已在 Constellation 消息中）
	// ② 主题里说过的话（关联的所有 Moment）
	Moments []*Moment `protobuf:"bytes,2,rep,name=moments,proto3" json:"moments,omitempty"`
	// ③ 和那时的自己说说话（Star 列表，前端组装为 PastSelfCard）
	Stars         []*Star `protobuf:"bytes,3,rep,name=stars,proto3" json:"stars,omitempty"` // ④ ✦ 我想和你聊聊（topic_prompts 已在 Constellation 消息中）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConstellationRes) Reset() {
	*x = GetConstellationRes{}
	mi := &file_ego_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConstellationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConstellationRes) ProtoMessage() {}

func (x *GetConstellationRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConstellationRes.ProtoReflect.Descriptor instead.
func (*GetConstellationRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{28}
}

func (x *GetConstellationRes) GetConstellation() *Constellation {
	if x != nil {
		return x.Constellation
	}
	return nil
}

func (x *GetConstellationRes) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

func (x *GetConstellationRes) GetStars() []*Star {
	if x != nil {
		return x.Stars
	}
	return nil
}

type StartChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StarId        string                 `protobuf:"bytes,1,opt,name=star_id,json=starId,proto3" json:"star_id,omitempty"`                        // 对应一个 Star
	ChatSessionId string                 `protobuf:"bytes,2,opt,name=chat_session_id,json=chatSessionId,proto3" json:"chat_session_id,omitempty"` // 可选，传入旧 session_id 恢复对话
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartChatReq) Reset() {
	*x = StartChatReq{}
	mi := &file_ego_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatReq) ProtoMessage() {}

func (x *StartChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatReq.ProtoReflect.Descriptor instead.
func (*StartChatReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{29}
}

func (x *StartChatReq) GetStarId() string {
	if x != nil {
		return x.StarId
	}
	return ""
}

func (x *StartChatReq) GetChatSessionId() string {
	if x != nil {
		return x.ChatSessionId
	}
	return ""
}

type StartChatRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatSessionId string                 `protobuf:"bytes,1,opt,name=chat_session_id,json=chatSessionId,proto3" json:"chat_session_id,omitempty"`
	Opening       *ChatMessage           `protobuf:"bytes,2,opt,name=opening,proto3" json:"opening,omitempty"` // AI 开场白（新建时）或最后一条 AI 消息（恢复时）
	History       []*ChatMessage         `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"` // 恢复时返回历史消息，新建时为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartChatRes) Reset() {
	*x = StartChatRes{}
	mi := &file_ego_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatRes) ProtoMessage() {}

func (x *StartChatRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatRes.ProtoReflect.Descriptor instead.
func (*StartChatRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{30}
}

func (x *StartChatRes) GetChatSessionId() string {
	if x != nil {
		return x.ChatSessionId
	}
	return ""
}

func (x *StartChatRes) GetOpening() *ChatMessage {
	if x != nil {
		return x.Opening
	}
	return nil
}

func (x *StartChatRes) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatSessionId string                 `protobuf:"bytes,1,opt,name=chat_session_id,json=chatSessionId,proto3" json:"chat_session_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 用户发送的内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_ego_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{31}
}

func (x *SendMessageReq) GetChatSessionId() string {
	if x != nil {
		return x.ChatSessionId
	}
	return ""
}

func (x *SendMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         *ChatMessage           `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"` // AI（past-self）回复
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRes) Reset() {
	*x = SendMessageRes{}
	mi := &file_ego_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRes) ProtoMessage() {}

func (x *SendMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_ego_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRes.ProtoReflect.Descriptor instead.
func (*SendMessageRes) Descriptor() ([]byte, []int) {
	return file_ego_api_proto_rawDescGZIP(), []int{32}
}

func (x *SendMessageRes) GetReply() *ChatMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

var File_ego_api_proto protoreflect.FileDescriptor

const file_ego_api_proto_rawDesc = "" +
	"\n" +
	"\rego/api.proto\x12\x03ego\"@\n" +
	"\bLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\bLoginRes\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"l\n" +
	"\x06Moment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\x85\x01\n" +
	"\x04Echo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmoment_id\x18\x02 \x01(\tR\bmomentId\x12,\n" +
	"\x12matched_moment_ids\x18\x03 \x03(\tR\x10matchedMomentIds\x12\"\n" +
	"\fsimilarities\x18\x04 \x03(\x02R\fsimilarities\"\x91\x01\n" +
	"\aInsight\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmoment_id\x18\x02 \x01(\tR\bmomentId\x12\x17\n" +
	"\aecho_id\x18\x03 \x01(\tR\x06echoId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12,\n" +
	"\x12related_moment_ids\x18\x05 \x03(\tR\x10relatedMomentIds\"G\n" +
	"\x04Star\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"\x85\x02\n" +
	"\rConstellation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\x15constellation_insight\x18\x03 \x01(\tR\x14constellationInsight\x12\x19\n" +
	"\bstar_ids\x18\x04 \x03(\tR\astarIds\x12#\n" +
	"\rtopic_prompts\x18\x05 \x03(\tR\ftopicPrompts\x12\x1d\n" +
	"\n" +
	"star_count\x18\x06 \x01(\x05R\tstarCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xae\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04role\x18\x02 \x01(\x0e2\r.ego.ChatRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x124\n" +
	"\n" +
	"referenced\x18\x04 \x03(\v2\x14.ego.MomentReferenceR\n" +
	"referenced\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"?\n" +
	"\x0fMomentReference\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x18\n" +
	"\asnippet\x18\x02 \x01(\tR\asnippet\"F\n" +
	"\x0fCreateMomentReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"U\n" +
	"\x0fCreateMomentRes\x12#\n" +
	"\x06moment\x18\x01 \x01(\v2\v.ego.MomentR\x06moment\x12\x1d\n" +
	"\x04echo\x18\x02 \x01(\v2\t.ego.EchoR\x04echo\"!\n" +
	"\rGetMomentsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"6\n" +
	"\rGetMomentsRes\x12%\n" +
	"\amoments\x18\x01 \x03(\v2\v.ego.MomentR\amoments\"J\n" +
	"\x12GenerateInsightReq\x12\x1b\n" +
	"\tmoment_id\x18\x01 \x01(\tR\bmomentId\x12\x17\n" +
	"\aecho_id\x18\x02 \x01(\tR\x06echoId\"<\n" +
	"\x12GenerateInsightRes\x12&\n" +
	"\ainsight\x18\x01 \x01(\v2\f.ego.InsightR\ainsight\"\xa2\x01\n" +
	"\x05Trace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"motivation\x18\x02 \x01(\tR\n" +
	"motivation\x12\x18\n" +
	"\astashed\x18\x03 \x01(\bR\astashed\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x120\n" +
	"\x14first_moment_content\x18\x05 \x01(\tR\x12firstMomentContent\"y\n" +
	"\tTraceItem\x12#\n" +
	"\x06moment\x18\x01 \x01(\v2\v.ego.MomentR\x06moment\x12\x1f\n" +
	"\x05echos\x18\x02 \x03(\v2\t.ego.EchoR\x05echos\x12&\n" +
	"\ainsight\x18\x03 \x01(\v2\f.ego.InsightR\ainsight\"D\n" +
	"\rListTracesReq\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"o\n" +
	"\rListTracesRes\x12\"\n" +
	"\x06traces\x18\x01 \x03(\v2\n" +
	".ego.TraceR\x06traces\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\".\n" +
	"\x11GetTraceDetailReq\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"[\n" +
	"\x11GetTraceDetailRes\x12 \n" +
	"\x05trace\x18\x01 \x01(\v2\n" +
	".ego.TraceR\x05trace\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.ego.TraceItemR\x05items\"+\n" +
	"\x13GetRandomMomentsReq\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"<\n" +
	"\x13GetRandomMomentsRes\x12%\n" +
	"\amoments\x18\x01 \x03(\v2\v.ego.MomentR\amoments\"*\n" +
	"\rStashTraceReq\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\".\n" +
	"\rStashTraceRes\x12\x1d\n" +
	"\x04star\x18\x01 \x01(\v2\t.ego.StarR\x04star\"\x17\n" +
	"\x15ListConstellationsReq\"}\n" +
	"\x15ListConstellationsRes\x12:\n" +
	"\x0econstellations\x18\x01 \x03(\v2\x12.ego.ConstellationR\x0econstellations\x12(\n" +
	"\x10total_star_count\x18\x02 \x01(\x05R\x0etotalStarCount\"@\n" +
	"\x13GetConstellationReq\x12)\n" +
	"\x10constellation_id\x18\x01 \x01(\tR\x0fconstellationId\"\x97\x01\n" +
	"\x13GetConstellationRes\x128\n" +
	"\rconstellation\x18\x01 \x01(\v2\x12.ego.ConstellationR\rconstellation\x12%\n" +
	"\amoments\x18\x02 \x03(\v2\v.ego.MomentR\amoments\x12\x1f\n" +
	"\x05stars\x18\x03 \x03(\v2\t.ego.StarR\x05stars\"O\n" +
	"\fStartChatReq\x12\x17\n" +
	"\astar_id\x18\x01 \x01(\tR\x06starId\x12&\n" +
	"\x0fchat_session_id\x18\x02 \x01(\tR\rchatSessionId\"\x8e\x01\n" +
	"\fStartChatRes\x12&\n" +
	"\x0fchat_session_id\x18\x01 \x01(\tR\rchatSessionId\x12*\n" +
	"\aopening\x18\x02 \x01(\v2\x10.ego.ChatMessageR\aopening\x12*\n" +
	"\ahistory\x18\x03 \x03(\v2\x10.ego.ChatMessageR\ahistory\"R\n" +
	"\x0eSendMessageReq\x12&\n" +
	"\x0fchat_session_id\x18\x01 \x01(\tR\rchatSessionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"8\n" +
	"\x0eSendMessageRes\x12&\n" +
	"\x05reply\x18\x01 \x01(\v2\x10.ego.ChatMessageR\x05reply*>\n" +
	"\bChatRole\x12\x19\n" +
	"\x15CHAT_ROLE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\r\n" +
	"\tPAST_SELF\x10\x022\xdb\x05\n" +
	"\x03Ego\x12%\n" +
	"\x05Login\x12\r.ego.LoginReq\x1a\r.ego.LoginRes\x12:\n" +
	"\fCreateMoment\x12\x14.ego.CreateMomentReq\x1a\x14.ego.CreateMomentRes\x124\n" +
	"\n" +
	"GetMoments\x12\x12.ego.GetMomentsReq\x1a\x12.ego.GetMomentsRes\x12C\n" +
	"\x0fGenerateInsight\x12\x17.ego.GenerateInsightReq\x1a\x17.ego.GenerateInsightRes\x124\n" +
	"\n" +
	"ListTraces\x12\x12.ego.ListTracesReq\x1a\x12.ego.ListTracesRes\x12@\n" +
	"\x0eGetTraceDetail\x12\x16.ego.GetTraceDetailReq\x1a\x16.ego.GetTraceDetailRes\x12F\n" +
	"\x10GetRandomMoments\x12\x18.ego.GetRandomMomentsReq\x1a\x18.ego.GetRandomMomentsRes\x124\n" +
	"\n" +
	"StashTrace\x12\x12.ego.StashTraceReq\x1a\x12.ego.StashTraceRes\x12L\n" +
	"\x12ListConstellations\x12\x1a.ego.ListConstellationsReq\x1a\x1a.ego.ListConstellationsRes\x12F\n" +
	"\x10GetConstellation\x12\x18.ego.GetConstellationReq\x1a\x18.ego.GetConstellationRes\x121\n" +
	"\tStartChat\x12\x11.ego.StartChatReq\x1a\x11.ego.StartChatRes\x127\n" +
	"\vSendMessage\x12\x13.ego.SendMessageReq\x1a\x13.ego.SendMessageResB\x16Z\x14ego-server/proto/egob\x06proto3"

var (
	file_ego_api_proto_rawDescOnce sync.Once
	file_ego_api_proto_rawDescData []byte
)

func file_ego_api_proto_rawDescGZIP() []byte {
	file_ego_api_proto_rawDescOnce.Do(func() {
		file_ego_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ego_api_proto_rawDesc), len(file_ego_api_proto_rawDesc)))
	})
	return file_ego_api_proto_rawDescData
}

var file_ego_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ego_api_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_ego_api_proto_goTypes = []any{
	(ChatRole)(0),                 // 0: ego.ChatRole
	(*LoginReq)(nil),              // 1: ego.LoginReq
	(*LoginRes)(nil),              // 2: ego.LoginRes
	(*Moment)(nil),                // 3: ego.Moment
	(*Echo)(nil),                  // 4: ego.Echo
	(*Insight)(nil),               // 5: ego.Insight
	(*Star)(nil),                  // 6: ego.Star
	(*Constellation)(nil),         // 7: ego.Constellation
	(*ChatMessage)(nil),           // 8: ego.ChatMessage
	(*MomentReference)(nil),       // 9: ego.MomentReference
	(*CreateMomentReq)(nil),       // 10: ego.CreateMomentReq
	(*CreateMomentRes)(nil),       // 11: ego.CreateMomentRes
	(*GetMomentsReq)(nil),         // 12: ego.GetMomentsReq
	(*GetMomentsRes)(nil),         // 13: ego.GetMomentsRes
	(*GenerateInsightReq)(nil),    // 14: ego.GenerateInsightReq
	(*GenerateInsightRes)(nil),    // 15: ego.GenerateInsightRes
	(*Trace)(nil),                 // 16: ego.Trace
	(*TraceItem)(nil),             // 17: ego.TraceItem
	(*ListTracesReq)(nil),         // 18: ego.ListTracesReq
	(*ListTracesRes)(nil),         // 19: ego.ListTracesRes
	(*GetTraceDetailReq)(nil),     // 20: ego.GetTraceDetailReq
	(*GetTraceDetailRes)(nil),     // 21: ego.GetTraceDetailRes
	(*GetRandomMomentsReq)(nil),   // 22: ego.GetRandomMomentsReq
	(*GetRandomMomentsRes)(nil),   // 23: ego.GetRandomMomentsRes
	(*StashTraceReq)(nil),         // 24: ego.StashTraceReq
	(*StashTraceRes)(nil),         // 25: ego.StashTraceRes
	(*ListConstellationsReq)(nil), // 26: ego.ListConstellationsReq
	(*ListConstellationsRes)(nil), // 27: ego.ListConstellationsRes
	(*GetConstellationReq)(nil),   // 28: ego.GetConstellationReq
	(*GetConstellationRes)(nil),   // 29: ego.GetConstellationRes
	(*StartChatReq)(nil),          // 30: ego.StartChatReq
	(*StartChatRes)(nil),          // 31: ego.StartChatRes
	(*SendMessageReq)(nil),        // 32: ego.SendMessageReq
	(*SendMessageRes)(nil),        // 33: ego.SendMessageRes
}
var file_ego_api_proto_depIdxs = []int32{
	0,  // 0: ego.ChatMessage.role:type_name -> ego.ChatRole
	9,  // 1: ego.ChatMessage.referenced:type_name -> ego.MomentReference
	3,  // 2: ego.CreateMomentRes.moment:type_name -> ego.Moment
	4,  // 3: ego.CreateMomentRes.echo:type_name -> ego.Echo
	3,  // 4: ego.GetMomentsRes.moments:type_name -> ego.Moment
	5,  // 5: ego.GenerateInsightRes.insight:type_name -> ego.Insight
	3,  // 6: ego.TraceItem.moment:type_name -> ego.Moment
	4,  // 7: ego.TraceItem.echos:type_name -> ego.Echo
	5,  // 8: ego.TraceItem.insight:type_name -> ego.Insight
	16, // 9: ego.ListTracesRes.traces:type_name -> ego.Trace
	16, // 10: ego.GetTraceDetailRes.trace:type_name -> ego.Trace
	17, // 11: ego.GetTraceDetailRes.items:type_name -> ego.TraceItem
	3,  // 12: ego.GetRandomMomentsRes.moments:type_name -> ego.Moment
	6,  // 13: ego.StashTraceRes.star:type_name -> ego.Star
	7,  // 14: ego.ListConstellationsRes.constellations:type_name -> ego.Constellation
	7,  // 15: ego.GetConstellationRes.constellation:type_name -> ego.Constellation
	3,  // 16: ego.GetConstellationRes.moments:type_name -> ego.Moment
	6,  // 17: ego.GetConstellationRes.stars:type_name -> ego.Star
	8,  // 18: ego.StartChatRes.opening:type_name -> ego.ChatMessage
	8,  // 19: ego.StartChatRes.history:type_name -> ego.ChatMessage
	8,  // 20: ego.SendMessageRes.reply:type_name -> ego.ChatMessage
	1,  // 21: ego.Ego.Login:input_type -> ego.LoginReq
	10, // 22: ego.Ego.CreateMoment:input_type -> ego.CreateMomentReq
	12, // 23: ego.Ego.GetMoments:input_type -> ego.GetMomentsReq
	14, // 24: ego.Ego.GenerateInsight:input_type -> ego.GenerateInsightReq
	18, // 25: ego.Ego.ListTraces:input_type -> ego.ListTracesReq
	20, // 26: ego.Ego.GetTraceDetail:input_type -> ego.GetTraceDetailReq
	22, // 27: ego.Ego.GetRandomMoments:input_type -> ego.GetRandomMomentsReq
	24, // 28: ego.Ego.StashTrace:input_type -> ego.StashTraceReq
	26, // 29: ego.Ego.ListConstellations:input_type -> ego.ListConstellationsReq
	28, // 30: ego.Ego.GetConstellation:input_type -> ego.GetConstellationReq
	30, // 31: ego.Ego.StartChat:input_type -> ego.StartChatReq
	32, // 32: ego.Ego.SendMessage:input_type -> ego.SendMessageReq
	2,  // 33: ego.Ego.Login:output_type -> ego.LoginRes
	11, // 34: ego.Ego.CreateMoment:output_type -> ego.CreateMomentRes
	13, // 35: ego.Ego.GetMoments:output_type -> ego.GetMomentsRes
	15, // 36: ego.Ego.GenerateInsight:output_type -> ego.GenerateInsightRes
	19, // 37: ego.Ego.ListTraces:output_type -> ego.ListTracesRes
	21, // 38: ego.Ego.GetTraceDetail:output_type -> ego.GetTraceDetailRes
	23, // 39: ego.Ego.GetRandomMoments:output_type -> ego.GetRandomMomentsRes
	25, // 40: ego.Ego.StashTrace:output_type -> ego.StashTraceRes
	27, // 41: ego.Ego.ListConstellations:output_type -> ego.ListConstellationsRes
	29, // 42: ego.Ego.GetConstellation:output_type -> ego.GetConstellationRes
	31, // 43: ego.Ego.StartChat:output_type -> ego.StartChatRes
	33, // 44: ego.Ego.SendMessage:output_type -> ego.SendMessageRes
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_ego_api_proto_init() }
func file_ego_api_proto_init() {
	if File_ego_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ego_api_proto_rawDesc), len(file_ego_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ego_api_proto_goTypes,
		DependencyIndexes: file_ego_api_proto_depIdxs,
		EnumInfos:         file_ego_api_proto_enumTypes,
		MessageInfos:      file_ego_api_proto_msgTypes,
	}.Build()
	File_ego_api_proto = out.File
	file_ego_api_proto_goTypes = nil
	file_ego_api_proto_depIdxs = nil
}
