// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: ego/api.proto

package ego

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ego_Login_FullMethodName = "/ego.Ego/Login"
)

// EgoClient is the client API for Ego service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EgoClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
}

type egoClient struct {
	cc grpc.ClientConnInterface
}

func NewEgoClient(cc grpc.ClientConnInterface) EgoClient {
	return &egoClient{cc}
}

func (c *egoClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, Ego_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgoServer is the server API for Ego service.
// All implementations must embed UnimplementedEgoServer
// for forward compatibility.
type EgoServer interface {
	Login(context.Context, *LoginReq) (*LoginRes, error)
	mustEmbedUnimplementedEgoServer()
}

// UnimplementedEgoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgoServer struct{}

func (UnimplementedEgoServer) Login(context.Context, *LoginReq) (*LoginRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedEgoServer) mustEmbedUnimplementedEgoServer() {}
func (UnimplementedEgoServer) testEmbeddedByValue()             {}

// UnsafeEgoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgoServer will
// result in compilation errors.
type UnsafeEgoServer interface {
	mustEmbedUnimplementedEgoServer()
}

func RegisterEgoServer(s grpc.ServiceRegistrar, srv EgoServer) {
	// If the following call panics, it indicates UnimplementedEgoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ego_ServiceDesc, srv)
}

func _Ego_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ego_ServiceDesc is the grpc.ServiceDesc for Ego service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ego_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ego.Ego",
	HandlerType: (*EgoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Ego_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ego/api.proto",
}
