// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: ego/api.proto

package ego

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ego_Login_FullMethodName              = "/ego.Ego/Login"
	Ego_CreateMoment_FullMethodName       = "/ego.Ego/CreateMoment"
	Ego_ListMoments_FullMethodName        = "/ego.Ego/ListMoments"
	Ego_GetRandomMoments_FullMethodName   = "/ego.Ego/GetRandomMoments"
	Ego_GenerateInsight_FullMethodName    = "/ego.Ego/GenerateInsight"
	Ego_StashTrace_FullMethodName         = "/ego.Ego/StashTrace"
	Ego_ListConstellations_FullMethodName = "/ego.Ego/ListConstellations"
	Ego_GetConstellation_FullMethodName   = "/ego.Ego/GetConstellation"
	Ego_StartChat_FullMethodName          = "/ego.Ego/StartChat"
	Ego_SendMessage_FullMethodName        = "/ego.Ego/SendMessage"
)

// EgoClient is the client API for Ego service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EgoClient interface {
	// ─── Auth（认证）─────────────────────────────────────
	// 登录/自动注册，返回 JWT token
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
	// ─── Moment（话语）─────────────────────────────────────
	// 写下一句话，同时获取回声推荐
	CreateMoment(ctx context.Context, in *CreateMomentReq, opts ...grpc.CallOption) (*CreateMomentRes, error)
	// 获取过往时间线（按月分组，游标分页）
	ListMoments(ctx context.Context, in *ListMomentsReq, opts ...grpc.CallOption) (*ListMomentsRes, error)
	// 获取随机 N 条历史话语（记忆光点盲盒）
	GetRandomMoments(ctx context.Context, in *GetRandomMomentsReq, opts ...grpc.CallOption) (*GetRandomMomentsRes, error)
	// ─── Insight（我发现）──────────────────────────────────
	// 生成 AI 观察
	GenerateInsight(ctx context.Context, in *GenerateInsightReq, opts ...grpc.CallOption) (*GenerateInsightRes, error)
	// ─── Stash（收进星图）─────────────────────────────────
	// 将一次完整的 Trace 收进星图，生成星星并重评估星座
	StashTrace(ctx context.Context, in *StashTraceReq, opts ...grpc.CallOption) (*StashTraceRes, error)
	// ─── Constellation（星座）──────────────────────────────
	// 获取所有星座列表（星图页渲染用）
	ListConstellations(ctx context.Context, in *ListConstellationsReq, opts ...grpc.CallOption) (*ListConstellationsRes, error)
	// 获取星座详情（含观察、对话卡片、话题引子）
	GetConstellation(ctx context.Context, in *GetConstellationReq, opts ...grpc.CallOption) (*GetConstellationRes, error)
	// ─── Chat（和那时的自己说说话）──────────────────────────
	// 开始一次对话（后端构建 past-self 上下文）
	StartChat(ctx context.Context, in *StartChatReq, opts ...grpc.CallOption) (*StartChatRes, error)
	// 发送消息并获取回复
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageRes, error)
}

type egoClient struct {
	cc grpc.ClientConnInterface
}

func NewEgoClient(cc grpc.ClientConnInterface) EgoClient {
	return &egoClient{cc}
}

func (c *egoClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, Ego_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) CreateMoment(ctx context.Context, in *CreateMomentReq, opts ...grpc.CallOption) (*CreateMomentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMomentRes)
	err := c.cc.Invoke(ctx, Ego_CreateMoment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) ListMoments(ctx context.Context, in *ListMomentsReq, opts ...grpc.CallOption) (*ListMomentsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMomentsRes)
	err := c.cc.Invoke(ctx, Ego_ListMoments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) GetRandomMoments(ctx context.Context, in *GetRandomMomentsReq, opts ...grpc.CallOption) (*GetRandomMomentsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRandomMomentsRes)
	err := c.cc.Invoke(ctx, Ego_GetRandomMoments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) GenerateInsight(ctx context.Context, in *GenerateInsightReq, opts ...grpc.CallOption) (*GenerateInsightRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateInsightRes)
	err := c.cc.Invoke(ctx, Ego_GenerateInsight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) StashTrace(ctx context.Context, in *StashTraceReq, opts ...grpc.CallOption) (*StashTraceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StashTraceRes)
	err := c.cc.Invoke(ctx, Ego_StashTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) ListConstellations(ctx context.Context, in *ListConstellationsReq, opts ...grpc.CallOption) (*ListConstellationsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConstellationsRes)
	err := c.cc.Invoke(ctx, Ego_ListConstellations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) GetConstellation(ctx context.Context, in *GetConstellationReq, opts ...grpc.CallOption) (*GetConstellationRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConstellationRes)
	err := c.cc.Invoke(ctx, Ego_GetConstellation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) StartChat(ctx context.Context, in *StartChatReq, opts ...grpc.CallOption) (*StartChatRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartChatRes)
	err := c.cc.Invoke(ctx, Ego_StartChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egoClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageRes)
	err := c.cc.Invoke(ctx, Ego_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgoServer is the server API for Ego service.
// All implementations must embed UnimplementedEgoServer
// for forward compatibility.
type EgoServer interface {
	// ─── Auth（认证）─────────────────────────────────────
	// 登录/自动注册，返回 JWT token
	Login(context.Context, *LoginReq) (*LoginRes, error)
	// ─── Moment（话语）─────────────────────────────────────
	// 写下一句话，同时获取回声推荐
	CreateMoment(context.Context, *CreateMomentReq) (*CreateMomentRes, error)
	// 获取过往时间线（按月分组，游标分页）
	ListMoments(context.Context, *ListMomentsReq) (*ListMomentsRes, error)
	// 获取随机 N 条历史话语（记忆光点盲盒）
	GetRandomMoments(context.Context, *GetRandomMomentsReq) (*GetRandomMomentsRes, error)
	// ─── Insight（我发现）──────────────────────────────────
	// 生成 AI 观察
	GenerateInsight(context.Context, *GenerateInsightReq) (*GenerateInsightRes, error)
	// ─── Stash（收进星图）─────────────────────────────────
	// 将一次完整的 Trace 收进星图，生成星星并重评估星座
	StashTrace(context.Context, *StashTraceReq) (*StashTraceRes, error)
	// ─── Constellation（星座）──────────────────────────────
	// 获取所有星座列表（星图页渲染用）
	ListConstellations(context.Context, *ListConstellationsReq) (*ListConstellationsRes, error)
	// 获取星座详情（含观察、对话卡片、话题引子）
	GetConstellation(context.Context, *GetConstellationReq) (*GetConstellationRes, error)
	// ─── Chat（和那时的自己说说话）──────────────────────────
	// 开始一次对话（后端构建 past-self 上下文）
	StartChat(context.Context, *StartChatReq) (*StartChatRes, error)
	// 发送消息并获取回复
	SendMessage(context.Context, *SendMessageReq) (*SendMessageRes, error)
	mustEmbedUnimplementedEgoServer()
}

// UnimplementedEgoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgoServer struct{}

func (UnimplementedEgoServer) Login(context.Context, *LoginReq) (*LoginRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedEgoServer) CreateMoment(context.Context, *CreateMomentReq) (*CreateMomentRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMoment not implemented")
}
func (UnimplementedEgoServer) ListMoments(context.Context, *ListMomentsReq) (*ListMomentsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMoments not implemented")
}
func (UnimplementedEgoServer) GetRandomMoments(context.Context, *GetRandomMomentsReq) (*GetRandomMomentsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRandomMoments not implemented")
}
func (UnimplementedEgoServer) GenerateInsight(context.Context, *GenerateInsightReq) (*GenerateInsightRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateInsight not implemented")
}
func (UnimplementedEgoServer) StashTrace(context.Context, *StashTraceReq) (*StashTraceRes, error) {
	return nil, status.Error(codes.Unimplemented, "method StashTrace not implemented")
}
func (UnimplementedEgoServer) ListConstellations(context.Context, *ListConstellationsReq) (*ListConstellationsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConstellations not implemented")
}
func (UnimplementedEgoServer) GetConstellation(context.Context, *GetConstellationReq) (*GetConstellationRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConstellation not implemented")
}
func (UnimplementedEgoServer) StartChat(context.Context, *StartChatReq) (*StartChatRes, error) {
	return nil, status.Error(codes.Unimplemented, "method StartChat not implemented")
}
func (UnimplementedEgoServer) SendMessage(context.Context, *SendMessageReq) (*SendMessageRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedEgoServer) mustEmbedUnimplementedEgoServer() {}
func (UnimplementedEgoServer) testEmbeddedByValue()             {}

// UnsafeEgoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgoServer will
// result in compilation errors.
type UnsafeEgoServer interface {
	mustEmbedUnimplementedEgoServer()
}

func RegisterEgoServer(s grpc.ServiceRegistrar, srv EgoServer) {
	// If the following call panics, it indicates UnimplementedEgoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ego_ServiceDesc, srv)
}

func _Ego_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_CreateMoment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMomentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).CreateMoment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_CreateMoment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).CreateMoment(ctx, req.(*CreateMomentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_ListMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMomentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).ListMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_ListMoments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).ListMoments(ctx, req.(*ListMomentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_GetRandomMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomMomentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).GetRandomMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_GetRandomMoments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).GetRandomMoments(ctx, req.(*GetRandomMomentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_GenerateInsight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInsightReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).GenerateInsight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_GenerateInsight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).GenerateInsight(ctx, req.(*GenerateInsightReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_StashTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StashTraceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).StashTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_StashTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).StashTrace(ctx, req.(*StashTraceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_ListConstellations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConstellationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).ListConstellations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_ListConstellations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).ListConstellations(ctx, req.(*ListConstellationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_GetConstellation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConstellationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).GetConstellation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_GetConstellation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).GetConstellation(ctx, req.(*GetConstellationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_StartChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).StartChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_StartChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).StartChat(ctx, req.(*StartChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ego_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgoServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ego_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgoServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ego_ServiceDesc is the grpc.ServiceDesc for Ego service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ego_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ego.Ego",
	HandlerType: (*EgoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Ego_Login_Handler,
		},
		{
			MethodName: "CreateMoment",
			Handler:    _Ego_CreateMoment_Handler,
		},
		{
			MethodName: "ListMoments",
			Handler:    _Ego_ListMoments_Handler,
		},
		{
			MethodName: "GetRandomMoments",
			Handler:    _Ego_GetRandomMoments_Handler,
		},
		{
			MethodName: "GenerateInsight",
			Handler:    _Ego_GenerateInsight_Handler,
		},
		{
			MethodName: "StashTrace",
			Handler:    _Ego_StashTrace_Handler,
		},
		{
			MethodName: "ListConstellations",
			Handler:    _Ego_ListConstellations_Handler,
		},
		{
			MethodName: "GetConstellation",
			Handler:    _Ego_GetConstellation_Handler,
		},
		{
			MethodName: "StartChat",
			Handler:    _Ego_StartChat_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Ego_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ego/api.proto",
}
