ALTER TABLE constellation_profiles
ADD COLUMN IF NOT EXISTS theme_code TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS theme_label TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS theme_description TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS theme_examples JSONB NOT NULL DEFAULT '[]'::JSONB;
